### ISSUE TITLE
get_camera_params() returns a dictionary that is not accepted by set_camera()

### ISSUE THREAD

**Issue by horsto** [BrancoLab/brainrender#100]
**Describe the bug**
The function `get_camera_params()` returns a dictionary with keys  `['position', 'focal_point', 'view_up', 'distance', 'clipping_range', 'orientation']`. When trying to `set_camera()` a dictionary with keys `['position', 'focal', 'viewup', 'distance', 'clipping']` is expected. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender/Utils/camera.py", line 141, in set_camera
    camera = check_camera_param(camera)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender/Utils/camera.py", line 75, in check_camera_param
    f"Camera parameters dict should include the following keys: {params}"
ValueError: Camera parameters dict should include the following keys: ['position', 'focal', 'viewup', 'distance', 'clipping']
```

**To Reproduce**
```
from brainrender.scene import Scene
from brainrender.render import get_camera_params, set_camera

scene = Scene(add_root=None)
camera_dict = get_camera_params(scene)
set_camera(scene, camera_dict)
```

**Expected behavior**
I think it would be better if the returned dictionary has the same keys as the one fed back in to set camera (?).
The camera handling is explained well in `Examples/basic/camera.py`. But if one wants to change parameters (e.g. only one of the entries is updated), it is easier if the dictionaries match.

**Comment by FedeClaudi** [comment]
Hey, that's correct it doesn't make sense for them to be using different keys. I will fix that in the next release, thanks!

**Comment by FedeClaudi** [comment]
This has been fixed and will be released [with the next version](https://github.com/BrancoLab/brainrender/issues/104) of `brainrender`
