### ISSUE TITLE
Statistical map visualisation

### ISSUE THREAD

**Issue by estellenassar** [BrancoLab/brainrender#105]
Hello,

I have this t-statistic map that I am attempting to visualise in 3D. This is what my scene currently looks like:

![Screenshot 2020-09-02 at 00 50 19](https://user-images.githubusercontent.com/35455537/91916901-4855b180-ecb6-11ea-8293-c1f9bb56110e.png)

I registered the t-map to the Allen Reference Atlas (ARA) found [here](http://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/average_template/). I wanted to ask what brain volume you are using to create the shell (apologies if this is stated somewhere). I first assumed it would be the ARA, but if so, I'm not sure why the t-map is not overlaying the shell.

EDIT: Apologies, I found the error causing the different orientations!

After I sort that out, visualising this t-map in a way that is legible is the tricky part! I looked through your examples and I don't think there is anything available for this yet. I was thinking of colour coding zones in which the t-values are between a certain range. For example, where tmax is 7, the t-values between 5 and 7 would be red, the t-values between 3-5 would be orange, etc. To make this more visible, the red can be the most opaque, and the other zones can gradually become more transparent.

I am aware that I could maybe do this by splitting the t-map into these different regions myself, and tweak with the colour and opacity when uploading them onto the scene. But do you think there is a simpler way to do this?

Thank you for your help!

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for getting in touch, and cool dataset!

The mouse atlas is indeed from the ARA, but it's a version that is supported by [brainglobe's atlas API](https://github.com/brainglobe/bg-atlasapi). As such, the orientation and origin of the atlas might be different from from the default ARA's one.
Let me ping the expert (@vigji ) on [bg-space](https://github.com/brainglobe/bg-space) who might be able to say more about what's going on here. I might be able to give you more info on this tomorrow morning, with a fresher brain.. 

Keep in mind that currently `brainrender` mirriors the left and right hemispheres, but [we're in the process of fix this](https://github.com/brainglobe/bg-atlasapi/issues/73). 




-----

For the visualization, how is your data structured? Is it a 3d volume with a p-value at each voxel?

If so, perhap's the best way is to use [vedo](https://github.com/marcomusy/vedo) to load it as a `Volume` and from that get a `legosurface`. This is an example of what it looks like for gene expression data:
![image](https://user-images.githubusercontent.com/17436313/91919007-7f2ec600-ecbc-11ea-84cd-4e202bbeb013.png)

[see examples here](https://docs.brainrender.info/overview/examples) or this example in [vedo](https://github.com/marcomusy/vedo/blob/2b585cb9993f0fe0aa394421fc237dd7550aecb2/examples/volumetric/legosurface.py). 

Using `legosurface` you can threshold values in a range and color voxels (and I think change alpha) according to the p-value of each voxel. 

The alternative is to use the vedo `Volume` to find regions in a given value range and extract meshes from those, then render these meshes in brainrender. This can also be done in a couple lines of code, you should find examples in the issues in `vedo`'s github page. 


Hope this helps.

**Comment by vigji** [comment]
Hi @estellenassar !
So, the meshes that `brainrender` uses come from `bg-atlasapi` as @FedeClaudi said, and we are preserving there the original axis order from the ARA: 1st antero-posterior, 2nd superior-inferior, 3rd left-right (actually right-left, in the numpy stack they provide, this is what raised the problems @FedeClaudi mentioned). In the 100um brain, this correspond to a stack of size (132, 80, 114), as in the one that you linked, and it matches what we have in `bg-atlasapi`.

Looking at your data, it seems that your stack  axis is the following: left-right, superior-inferior, anterior-posterior. Can you confirm this?

I know that the nrrd file can be funny: loading, the same file with the python nrrd module and in ImageJ will produce different results (ImageJ-loaded file is 114, 80, 132, with first and last axes switched). Can you confirm this happens in your stack as well? How are you loading and aligning to the ARA reference?
The solution would either to register to the ARA reference using the `bg-atlasapi` API (basic usage instructions [here](https://github.com/brainglobe/bg-atlasapi)) where the ambiguity is solved and the stack matches ARA description of the space; or you can reorient your stack, manually, or with the [bg-space](https://github.com/brainglobe/bg-space) utility

**Comment by vigji** [comment]
By the way, I had a look at the header of the nrrd file that provide and now I am very confused. It says 
```
('space', 'left-posterior-superior'),
('sizes', array([132,  80, 114])),
```
So `space` does not match neither the [CCFv3 specification](http://help.brain-map.org/display/mouseconnectivity/API), which should be Posterior-Inferior-Right, nor the stack size (123 voxels is Anterior-Posterior). So don't know if you're counting on that header but I would not - I will try to ask them about it.

**Comment by adamltyson** [comment]
Hi @estellenassar. Just chiming in here, as I'm interested in the same problem, visualising heatmaps from [cellfinder](https://github.com/SainsburyWellcomeCentre/cellfinder), registered to the [brainglobe atlases](https://github.com/brainglobe/bg-atlasapi) (with [brainreg](https://github.com/brainglobe/brainreg)) in brainrender. 

There may be some common ground, looking into how best to visualise this kind of stuff. Out of interest, how are you registering your data to the CCF?

**Comment by estellenassar** [comment]
@FedeClaudi Thank you for the details! I was away the last few weeks, and seem to have missed this new `legosurface` feature. I will also definitely try my hand at finding the regions in a given value range with veto Volume.

---

@vigji I apologise, I was using one of the example scripts, and just realised that I forgot to comment out some rotate & scale lines! They're were hidden away between comments, and I forgot they were there. I'm sorry for wasting your time on this! Something's definition wrong with that header then.

I also forgot to mention that I used the 25um template for the registration, which would've been a key giveaway as to the scaling going on! With `tmap.scale([500, 500, 500])`, this is the scene I end up with:

![Screenshot 2020-09-02 at 13 49 56](https://user-images.githubusercontent.com/35455537/91983168-34946480-ed23-11ea-8199-13cfe13d3012.png)

If I register my data to the 100um template, I assume I won't need to scale the resulting t-map?

---

@adamltyson I am currently using [ANTs](https://github.com/ANTsX/ANTs)' antsRegistrationSyN.sh script to register to the ARA (I found out that orientation wasn't an issue, it was just my mistake). Great to know that we are working on visualising similar data, and it would be nice to know if you end up doing something different to the methods described by @FedeClaudi.

**Comment by FedeClaudi** [comment]
Hi, 

`brainrender`'s units are in micrometers. So if you have your volume registered to say the 25um version of the atlas, you'll have to scale things by 25 to match `brainrender`'s scale. If you're using `vedo`'s [`Volume` class](https://github.com/marcomusy/vedo/blob/17196b46b3943bfbb982f2de0787e277a3cac56a/vedo/volume.py#L223), you can specify a `voxel scale` when loading the volume. this should take care of it. 

I do the same to visualize the gene data, the gene expression intensity maps are defined with voxels of 200um so I need to scale the `Volume` accordingly with fit with the rest of the visualization: 
https://github.com/BrancoLab/brainrender/blob/4c087bc4cb8f94ba394dc0cf75baa646065ea44b/brainrender/ABA/gene_expression/api.py#L210

incidentally, the same function linked above takes care of creating the `legosurface` as well :P

**Comment by estellenassar** [comment]
Okay it makes sense now, I converted the ARA to mm to match my data, and that's why it's so tiny on brainrender. I'll convert my data to um instead, and that should fix the problem. And that's a nice trick to know for if I want to keep using the 25um template.

If there is nothing else to add, you can close the issue. Thanks a lot for your help!

**Comment by FedeClaudi** [comment]
Okay, great! Hope this all works out and you get some awesome visualization from your data. 
If you encounter any other problem, or would like to see some feature added to `brainrender` give me a shout!
