### ISSUE TITLE
as a widget?

### ISSUE THREAD

**Issue by bendichter** [BrancoLab/brainrender#111]
I'd really like to be able to use brainrender in [NWBWidgets](https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets). Would it be possible to output an interactive window as a widget, similar to [ccfwidget](https://github.com/NeurodataWithoutBorders/ccf-widget/tree/master/ccfwidget)?

**Comment by FedeClaudi** [comment]
Hi, that'd be great!

`brainrender` relies on [vedo](https://github.com/marcomusy/vedo) which does work in jupyter notebooks. This should also get better as vtk gets better integrated with `jupyter` [see ipyvtk](https://github.com/Kitware/ipyvtk-simple).

Beyond rendering an interactive visualization in jupyter, what would you need to turn this into a useful widget?

**Comment by bendichter** [comment]
Let me test out the jupyter functionality that currently exists. I'm looking at the docs...

In this page: https://docs.brainrender.info/usage/using-notebooks#embedding-renderings-in-jupyter-notebooks

where do I import `show` from? And I guess I can combine this with any of the examples in https://github.com/BrancoLab/brainrender/tree/master/Examples?

**Comment by bendichter** [comment]
OK, I got the tutorial working (PR [here](https://github.com/FedeClaudi/brainrender-docs/pull/1)). Now would it be possible to put this inside an HBox? e.g.

```python
from ipywidgets import HBox, Button
HBox([Button(description='hi'), brainrender_object])
```

**Comment by FedeClaudi** [comment]
I've added an example [notebook](https://github.com/BrancoLab/brainrender/blob/master/notebook_workflow.ipynb), sorry that the documentation on notebooks is still a bit sketchy. 

Honestly, I don't really know I don't have much experience with this kind of things. 
Perhaps @marcomusy (deveoper of `vedo`) know more about this?

**Comment by marcomusy** [comment]
Hi I'm not sure how HBox renders in a notebook. At the moment `vedo` detects the jupyter environment and delegates the rendering to either `k3d`, `panel` or `itkwidgets`

**Comment by bendichter** [comment]
It's alive!

For posterity:

```python
from vtkplotter import embedWindow, show

embedWindow('itkwidgets')

import brainrender

brainrender.SHADER_STYLE = "cartoon"
from brainrender.scene import Scene

# Create a scene
scene = Scene(title="brain regions")

# Add the whole thalamus in gray
scene.add_brain_regions(["TH"], alpha=0.15)

# Add VAL nucleus in wireframe style with the allen color
val = scene.add_brain_regions(["VAL"], use_original_color=True)
val.wireframe()

scene.render()

from ipywidgets import VBox, Button
VBox([Button(description='hi'), show(scene.actors)])
```

**Comment by FedeClaudi** [comment]
Awesome, thanks @bendichter, please keep me posted on this, should you integrate it with NWBwidgets.

And thanks for the help Marco.

**Comment by FedeClaudi** [comment]
@bendichter would it be okay if I added this to the docs as an alternative example for using brainrender in notebooks?

**Comment by bendichter** [comment]
@FedeClaudi yes, go for it!

**Comment by bendichter** [comment]
@marcomusy, is there a convenient way to give these better names?
![image](https://user-images.githubusercontent.com/844306/95635872-a3b85380-0a5b-11eb-89c3-9fa13b5e9af3.png)

**Comment by marcomusy** [comment]
well in vedo all objects have the attribute `name`

**Comment by FedeClaudi** [comment]
In the next release (https://github.com/BrancoLab/brainrender/issues/104) meshes will have a name according to what they are.
