### ISSUE TITLE
reviewing examples

### ISSUE THREAD

**Issue by marcomusy** [BrancoLab/BrainRender#14]
Hi, first off ,thanks for using `vtkplotter`! :)
I went through the examples and I found a bunch of possible problems:

in Example/Cells.ipynb
![Cells_err1](https://user-images.githubusercontent.com/32848391/69637870-d0d56080-1059-11ea-8498-7d8de8ecc58d.png)

in Misc.ipynb no slider is shoowing in the rendering window
![Misc_noslider](https://user-images.githubusercontent.com/32848391/69637908-e8ace480-1059-11ea-89c2-9f1480568654.png)
(this might be due to my local version of vtkplotter, I might have broken some functionality..)

In Regions.ipynb:
![Regions](https://user-images.githubusercontent.com/32848391/69638001-227deb00-105a-11ea-8aa8-49898f437b33.png)
Also update_folder doesn't seem to exist..

In Video.ipynb i get:
![Video](https://user-images.githubusercontent.com/32848391/69638086-51945c80-105a-11ea-98d3-99a7abd44b74.png)

Besides, I have a few suggestions to maybe improve the interface i.e.
- can add rendering window titles with `Plotter(title='BrainRender version x.x')`
- consider Plotter shape descriptors "1|3", "3|1", "2/3", this is a new feature that allows to subdivide rendering spaces asymmetrically.
- can set position of the Scene / Plotter instance with Plotter(pos=(x_screen,y_screen)` when having multiple windows
- Some examples take quite a long to download + render, maybe it is a good idea to indicate in the example the approx time for the user to wait or use a `ProgressBar`
- the iconized whole brain (very nice idea btw!) shows up a bit too high in the rendering window
- add some method to close window (maybe a button with status color, or `a scene.close()` method). I;m not sure if there is the possibility to disable 'q' on keyboard as this hangs the execution..
- Neuron.ipynb takes ages to load a nr of neurons.. maybe could be made faster by reducing the amount of stuff to download, or is it expected or necessary at all?
- Consider not rendering the empty Scene() when creating the instance, as probably it is not necessary..

ignore any of these which you consider irrelevant or let me know if you need clarifications or help :)
Cheers
Marco

**Comment by FedeClaudi** [comment]
Hi Marco, 

Thank you very much for your comments and spotting some bugs. I've been developing BrainRender after initially making the example notebooks, and it proved difficult to keep them updated and correctly working. I will look into the errors you've highlighted and fix them asap. 

And thank you for the ideas on how to make BR better. Some of them have been on my to-do list for a while, while others I hadn't  thought of (I'm still learning all that VTK plotter can do!).

I'll have to think how to implement some of this, but I'll just comment on the Neurons example.
The neuron's morphology data is provided as a json file with data on thousands of points defining the location of parts of the neuron. These need to be processed to crate a connected structure, and this processing takes a while. The rendering is actually pretty fast once the data have been processed. 
Once solution would be to make this happen in parallel when doing multiple neurons, but this proved not so easy for now. Alternatively I could cache the processed data and use them the next time the neurons are rendered, but I am not convinced yet that this is the best way to go. 

Thank you again for the advice, and thank you so much for making VTK plotter, it's such a brilliant piece of software, and a real pleasure to use :)

**Comment by FedeClaudi** [comment]
Hi Marco,

The errors in the examples should be fixed now. Thank you again for spotting them and reporting them!

Cheers, 
Fede

**Comment by FedeClaudi** [comment]
Hi, 

With d026040c528d47e04979da64a268278503467d01 I've introduced caching for parsed neurons. 
Now rendering neurons is only slow the first time and very fast for subsequent renderings. 

Best Federico.

**Comment by marcomusy** [comment]
Hi Federico 
sounds great - do not hesitate to ask if you need any support on the vtkplotter fuctionality,
M.

**Comment by FedeClaudi** [comment]
Hi Marco, 

A bit of an odd question, is there a simple way to extract N random points inside the volume defined by a mesh using vtkplotter?

Cheers, 
Federico

**Comment by marcomusy** [comment]
Hi Federico, 
something like this would do?
```python
from vtkplotter import *
import numpy as np

pts = np.random.rand(5000, 3)

act = load(datadir+'bunny.obj').scale(10).alpha(0.1)

ipts = act.insidePoints(pts)
opts = act.insidePoints(pts, invert=True)
Points(ipts, c="g")
Points(opts, c="r")

print("inside  points #", len(ipts))
print("outside points #", len(opts))
show(..., bg='w')
```
![image](https://user-images.githubusercontent.com/32848391/70538698-d5723c80-1b62-11ea-8e78-675c44b273bc.png)

M.

**Comment by FedeClaudi** [comment]
awesome, thank you so much!

**Comment by FedeClaudi** [comment]
Hi Marco, sorry to bother you again. 

Could you have a look at https://github.com/BrancoLab/BrainRender/issues/18#issue-536468176 when you have a moment?

It seems that when multiple scenes are created one after the other, the actors are upside down from the second scene onwards. I don't think that this has anything to do with brain render per se, but I can't tell what's causing this either. If you could look into it that would be awesome, as the current fix for it is suboptimal.
