### ISSUE TITLE
Docstrings and formatting

### ISSUE THREAD

**Issue by m-col** [BrancoLab/BrainRender#17]
I got BrainRender to print out some images and its working great!

I was wondering - are you following a standard for docstring formatting? I see that in most source files there is a consistent format but I don't recognise it.

It could nice in the future to get source-generated docs (e.g. using sphinx) using the docstrings.

**Comment by FedeClaudi** [comment]
Awesome!

I've used the style that was set by a visual studio code plugin to autogenerate doc strings, but not sure if it's an official one. 

Changing the style might be a bit of a pain, but it might also be worth it. Any idea on what style is best to use with sphinx, and if there are tools that automate the doctoring generation process?

**Comment by m-col** [comment]
Alright, in that case the plugin may have made it a known style. Does it
indicate a name for the style? Looking at the [sphinx docs](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html), it
can use (at least) their own sphinx format, Google's, and numpy's.

In any case, if it would require rewriting the docstrings that would definitely
be a pain, so I'm not suggesting we do so! My initial reason for mentioning this
was because they can be hard to read (see attached image) but this is super low
priority.

**Comment by m-col** [comment]
It seems github won't include images when attached to emails.

![img](https://user-images.githubusercontent.com/44536113/70616180-c09ab500-1c05-11ea-9432-f3af95e6c495.png)

**Comment by adamltyson** [comment]
Piggybacking of this, if BrainRender could use one of the official-ish python docstring formats (reST, numpy, google), it would make my life easier when I (eventually) try to some more work with it. Happy to help with any conversion process (however painful it might be).

**Comment by m-col** [comment]
I'd also be happy to help if you guys decided that it would be worth it.

It looks like the docstrings were made using [this plugin](https://github.com/NilsJPWerner/autoDocstring), and the format setting can be changed to different formats. It may be possible to simply change that setting and re-write them all. Also, [this page](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) has a nice comparison of those three docstring formats.

**Comment by FedeClaudi** [comment]
yep that is the plugin I used, and I just left it to default (docBlockr). It seems like it might be worth doing it, and the sooner the better as the codebase is not going to get any smaller. If decide on a format that would be best (hopefully supported by the plugin) I will start editing them.

**Comment by FedeClaudi** [comment]
So which format do we want to use for the docstrings?

**Comment by adamltyson** [comment]
I would prefer reST, but happy with either the google or numpy formats.

**Comment by FedeClaudi** [comment]
With a7f6d504b0cd3ad1f917f0f0eb5fe6c0ee2bf933 the docstrings have been updated to reST format. Let me see if you see anything missing/wrong with the docstrings.

Will close for now. 

Cheers, 
Fede
