### ISSUE TITLE
ResolvePackageNotFound: error during installation with the environment.yml file

### ISSUE THREAD

**Issue by siddjakes** [BrancoLab/BrainRender#2]
Hi,
So when I tried to install from the environment.yml file, it gives me the following error:
Solving environment: failed
ResolvePackageNotFound: 
  - readline==7.0=h1de35cc_5
  - libcxxabi==4.0.1=hcfea43d_1
  - xz==5.2.4=h1de35cc_4
  - openssl==1.1.1d=h1de35cc_1
  - libcxx==4.0.1=hcfea43d_1
  - sqlite==3.29.0=ha441bb4_0
  - libffi==3.2.1=h475c297_4
  - python==3.6.9=h359304d_0
  - tk==8.6.8=ha441bb4_0
  - zlib==1.2.11=h1de35cc_3
  - libedit==3.1.20181209=hb402a30_0
  - ncurses==6.1=h0a44026_1

Any guesses why?
 I could try moving these from the dependencies to pip and try it.

**Comment by FedeClaudi** [comment]
Hi, 

A quick look around suggests that this might be a problem with [conda](https://github.com/ContinuumIO/anaconda-issues/issues/9480).

A quick fix would be to manually install the packages listed [here](https://github.com/BrancoLab/BrainRender/blob/master/Installation/dependencies.txt).
It's just a few packages so should be okay. 

I will try to post a more stable solution in the coming days.

Bests, 
Federico

**Comment by siddjakes** [comment]
Thank you for the quick response Frederico. Since you had them in a .txt file, I just used the pip install -r dependencies.txt after creating the virtual env. Thank you! 

Siddharth
