### ISSUE TITLE
mouselight_fetch_neurons_metadata doesn't work with custom paths file.

### ISSUE THREAD

**Issue by adamltyson** [BrancoLab/BrainRender#22]
With `BrainRender.scene.Scene` or `BrainRender.Utils.ABA.connectome.ABA` I can specify `paths_file` if I have a custom `default_paths.yml`. I can't seem to do with with the mouselight functionality, so I get errors: `FileNotFoundError: Could not find file specifying folder paths: default_paths.yml`

**Comment by FedeClaudi** [comment]
Hi, when you mention the mouselight functionality do you refer to `BrainRender.Utils.parsers.mouselight`? The `NeuronsParser` class in it should accept a custom paths file: line 40 -  `Paths.__init__(self, paths_file=paths_file)`. 

Have you tried passing the complete path to the file?

**Comment by adamltyson** [comment]
I'm trying to follow the example [here](https://github.com/BrancoLab/BrainRender/blob/master/Examples/Neurons.ipynb). It fails at `neurons_metadata = mouselight_fetch_neurons_metadata(filterby='soma', filter_regions=['MOs'])`, and `mouselight_fetch_neurons_metadata` won't accept a `paths_file` argument.

**Comment by FedeClaudi** [comment]
`mouselight_fetch_neurons_metadata` returns a list with neurons metadata, it doesn't save anything so it doesn't need a `paths_file` argument. I don't get how your getting the `FileNotFoundError` above which is raised by `Paths`, `Paths` is not used by `mouselight_fetch_neurons_metadata`. The only thing that is saved as part of the mouse light neurons rendering is a `.vtk` file with the rendered neuron, to avoid parsing a Neuron's data every time it is rendered, but that should happen when you render the neurons (e.g. `scene.add_neurons(...)`.

This part of the example file above works for me:
```
# To download neurons, first we need to get metdata about the neurons in the database
neurons_metadata = mouselight_fetch_neurons_metadata()

# If instead we want to only get neurons whose soma is in a region of interest:
print("\nLet's get only the neurons in the secondary motor cortex.")
neurons_metadata = mouselight_fetch_neurons_metadata(filterby='soma', filter_regions=['MOs'])

# Then we can download the files and save them as a .json file
neurons_files =  download_neurons(neurons_metadata[:2]) # just saving the first couple neurons to speed things up
```

This is a minimal example on mouse light neurons rendering:
```
    scene = Scene()

    neurons_metadata = mouselight_fetch_neurons_metadata(filterby='soma', filter_regions=['MOp5'])
    neurons_files =  download_neurons(neurons_metadata[2:6]) 
    scene.add_neurons(neurons_files, soma_color='deepskyblue', force_to_hemisphere="right")

    scene.render()
```
If you pass a custom paths file to Scene in this example, does it produce the behaviour you need?

**Comment by adamltyson** [comment]
So firstly I think the issues I'm having are because I have brainrender pip installed straight from github (with `pip install git+https://github.com/BrancoLab/BrainRender`). Therefore the installed version of BrainRender doesn't have a `default_paths.yml` file. I think it's worth fixing this because:
a) Everything else in BrainRender that I've used works with a pip installed version.
b) Assuming you want to distribute BrainRender with PyPI/conda-forge, how BrainRender downloads data and finds the paths needs to be refactored a bit.

If (b) is not the case, then feel free to ignore this.

If I run the minimal example above, I get this error:

``` python
Querying MouseLight API...
     ... fetched metadata for 1094 neurons in 5.66s

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-dbd64d811052> in <module>
      1 scene = Scene(paths_file="/home/adam/brainrender/default_paths.yml")
      2 
----> 3 neurons_metadata = mouselight_fetch_neurons_metadata(filterby='soma', filter_regions=['MOp5'])
      4 neurons_files =  download_neurons(neurons_metadata[2:6])
      5 scene.add_neurons(neurons_files, soma_color='deepskyblue', force_to_hemisphere="right")

~/miniconda3/envs/pyclub/lib/python3.6/site-packages/BrainRender/Utils/MouseLightAPI/mouselight_info.py in mouselight_fetch_neurons_metadata(filterby, filter_regions, **kwargs)
    305 
    306                 # Get structure tree
--> 307                 aba = ABA()
    308                 ancestors_tree = aba.structure_tree.get_ancestor_id_map()
    309                 filter_regions_ids = [struct['id'] for struct in aba.structure_tree.get_structures_by_acronym(filter_regions)]

~/miniconda3/envs/pyclub/lib/python3.6/site-packages/BrainRender/Utils/ABA/connectome.py in __init__(self, projection_metric, paths_file)
     28         """ path_file {[str]} -- [Path to a YAML file specifying paths to data folders, to replace default paths] (default: {None}) """
     29 
---> 30         Paths.__init__(self, paths_file=paths_file)
     31 
     32         self.projection_metric = projection_metric

~/miniconda3/envs/pyclub/lib/python3.6/site-packages/BrainRender/Utils/paths_manager.py in __init__(self, paths_file)
     16 
     17         if not os.path.isfile(self.paths_file):
---> 18             raise FileNotFoundError("Could not find file specifying folder paths: {}".format(self.paths_file))
     19 
     20         # Parse paths file

FileNotFoundError: Could not find file specifying folder paths: default_paths.yml
```
I get the same error if I pass `paths_file` to `Scene`.

Finding the paths file is fixed if `paths_file` is passed to `mouselight_fetch_neurons_metadata` and then to `ABA()`, but it still doesn't play nicely with a custom paths file --- it has problems finding the directory save the `.json` files:

```python
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-a8233ef03094> in <module>
      2 
      3 neurons_metadata = mouselight_fetch_neurons_metadata(filterby='soma', filter_regions=['MOp5'], paths_file="/home/adam/brainrender/default_paths.yml")
----> 4 neurons_files =  download_neurons(neurons_metadata[2:6])
      5 scene.add_neurons(neurons_files, soma_color='deepskyblue', force_to_hemisphere="right")
      6 

~/miniconda3/envs/pyclub/lib/python3.6/site-packages/BrainRender/Utils/MouseLightAPI/mouselight_download_neurons.py in download_neurons(neurons_metadata)
    118 
    119                 # Save as  .json file: this means next time we don't have to download. Also it's necessary for the parser to render the neurons
--> 120                 make_json(neuron, file_path, axon_tracing=axon_tracing, dendrite_tracing=dendrite_tracing)
    121         return files

~/miniconda3/envs/pyclub/lib/python3.6/site-packages/BrainRender/Utils/MouseLightAPI/mouselight_download_neurons.py in make_json(neuron, file_path, axon_tracing, dendrite_tracing)
     74 
     75         # save to file
---> 76         with open(file_path, 'w') as f:
     77                 json.dump(content, f)
     78 

FileNotFoundError: [Errno 2] No such file or directory: 'Data/Morphology/MouseLight/AA0926.json
```

I haven't had time to look into how to fix this, but it's up to you I suppose whether you want to support pip installation, and maybe saving files in a separate location (that can be specified) a bit like amap, or whether you want to keep it as a source-code only thing via github.

**Comment by FedeClaudi** [comment]
okay, I think it would be good to have it working out of the box with conda/pip, but I'm unsure what is the best way to make the paths work. Maybe we can chat about it and come up with a working solution.

**Comment by FedeClaudi** [comment]
I've changed how the paths are managed (46c450059c0c909a9e422ba408cc50671a292c72), now it should be saving them locally and it should work for pip installed brain render. 

I've only tested it on Mac OSX though, so can't guarantee that it'll work on Linux or Windows.

**Comment by adamltyson** [comment]
This example now works fine on Linux.
