### ISSUE TITLE
scene.render() saves annotation._25.nrrd to current directory

### ISSUE THREAD

**Issue by adamltyson** [BrancoLab/BrainRender#25]
At least on my machine, `scene.render` saves a `Data` directory with the ARA annotation file into the current directory (all other files are saved into `.brainrender`).

Not a big problem, but annoying if you're moving around directories.

**Comment by FedeClaudi** [comment]
That's a mistake. It should be stored in `.brainrender` with the rest of the data, will fix thanks.

**Comment by FedeClaudi** [comment]
Fixed.
