### ISSUE TITLE
tqdm missing from environment.yml

### ISSUE THREAD

**Issue by raacampbell** [BrancoLab/BrainRender#3]
The tutorial notebook fails at `from BrainRender.scene import Scene` because tqdm is missing from the `environment.yml`. It's mentioned in `dependencies.txt` as per #2 .

After doing `conda install -c conda-forge tqdm` within the BrainRender Conda environment I can import `BrainRender.scene.Scene`. So I guess you can add it to `environment.yml` and it will avoid this problem.

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for reporting this. I will update the environment.yml files to fix the problem.
