### ISSUE TITLE
Tests are failing, so automatic deployment won't work.

### ISSUE THREAD

**Issue by adamltyson** [BrancoLab/BrainRender#34]
Tests on travis are failing. Need to fix these so we can set up automatic deployment to PyPI.

**Comment by FedeClaudi** [comment]
should be fixed with: 75edbcf9454ebd3989f7e1cee78989ecf5001e54

**Comment by adamltyson** [comment]
I think the segfault on Travis is due to the lack of a display on the test server. This can be imitated using [xvfb](https://en.wikipedia.org/wiki/Xvfb). Travis takes care of this, and I think #36 should fix the problem.
