### ISSUE TITLE
Add possibility to color cells based on the brain region they belong to

### ISSUE THREAD

**Issue by FedeClaudi** [BrancoLab/BrainRender#39]
This is mostly there, but buggy. 

It should be done by:

- using `ABA` to get the brain region each cell is in
- extracting the region's color
- creating a list of colors to pass when creating the `Spheres` actor.

**Comment by adamltyson** [comment]
Assuming this is linked to https://github.com/SainsburyWellcomeCentre/cellfinder/issues/15 (which I still haven't done). Can I make some of this easier by doing it in cellfinder, rather in brainrender?

p.s. feel free to bug me about issues that I haven't addressed yet.

**Comment by FedeClaudi** [comment]
yes and no. 

The `add_cells` function should be able to deal with two scenarios:

1. The user know already in which region each cell is (e.g. from cellfinder's output). In this case the region indicated by the user (e.g. by adding a 'region' column to the input dataframe) should be used to get the colors
2. The user doesn't know in which region each cell is. In this case the function should use `ABA.get_structure_from_coordinates` to get the region for each cell to use for specifying the color. `get_structure_from_coordinates` works already although it's not the fastest (it works for one cell at the time). 

At the moment the way inputs are passed to `add_cells` are a bit messy and the function doesn't handle the two scenarios very well, but I'll fix it soon.
