### ISSUE TITLE
Loading another brain at different age

### ISSUE THREAD

**Issue by anorak94** [BrancoLab/BrainRender#43]
Is it possible to use this package to view the brain in 3d at say p14 or p28 from the allen mouse brain atlas

**Comment by FedeClaudi** [comment]
Hi, 

This is not implemented yet, but it should fairly easy to do so. 
Does the Allen have 3D meshes for these brains (and an API to download them)?

**Comment by anorak94** [comment]
yeah i want to download and display the volumetric data at p4 
i dont know if the mesh is available or not but volumetric annotations and griddata etc are available but it should be possible to get the mesh from the volumetric data ?

**Comment by FedeClaudi** [comment]
Unfortunately this functionality is not supported. We will add code to visualise volumetric data soon, but it's not ready yet. 

I don't think that extraction of meshes from volumetric data will be part of brainrender functionality though, as that goes beyond visualisation of pre-analysed data.

**Comment by adamltyson** [comment]
This is something that should be in [neuro](https://GitHub.com/sainsburywellcomecentre/neuro), but likely won’t be user friendly and well integrated with brainrender for a while.
