### ISSUE TITLE
Integration with SHARP-Track, 

### ISSUE THREAD

**Issue by tbslv** [BrancoLab/BrainRender#44]
Hello, 

I was wondering if there is a possibility to fed the SHARPtrack (https://github.com/cortex-lab/allenCCF) algorithm output into BrainRender?

The output from ST can eiter be actual coordinates (rel. to Bregma, in mm) or points in a 10um reference space. 

Best
Tobi

**Comment by FedeClaudi** [comment]
Hi Tobi, 

Thanks for getting in touch. 
Yep, it should be possible. Brainrender doesn't use actual coordinates, but it should be able to use the point in the 10um reference space. 

You could then render a line or cylinder that goes through those points to mark the position of the probe, something like what I did in this figure ![this figure](https://raw.githubusercontent.com/BrancoLab/BrainREnder/master/Docs/Media/electrodes.png)

You could use the function `Scene.add_optic_cannula()` to get something similar for your that. If you'd like to render the probe in another manner we can come up with a better solution.  

Let me know if this works for you or if you need help with setting it up, if you want to send me an example of SHARP track's output I can play around with it. 

Thanks, 
Fede

**Comment by FedeClaudi** [comment]
If you know anyone that has an .stl or .obj file with the 3d rendering of the probe in principle we could display that in the correct location, but unfortunately I was unable to find so far.

**Comment by tbslv** [comment]
good morning fede, 

thanks a lot for the response and the advice. Using the points in the 10um reference space worked out (I had to included a scaling factor though ) 

Let me know if you're still intrested in SharpTrack data. 
Thanks for the software, I really like it! 

Best, 
Tobi

**Comment by FedeClaudi** [comment]
Hey awesome, I'm happy it worked out well! 
Yep, the scaling factor makes sense, did you have to multiply the coordinates by 10?
Did you use the function I suggested above in the end?

If you think that there's a better way to represent probe location let me know, I'd like to have functions specific for that.

Cheers, 
Fede

**Comment by tbslv** [comment]
Yes, the scaling factor is 10!

I ended up using the scene.add_cells function to render ''probe_points'' (SHARPtrack output), after that I have done a linear fit through these points and used the  linear function to render a cylinder from the surface of brain to the most ventral probe point. 
![Capture](https://user-images.githubusercontent.com/30258060/78119965-7eda8800-7409-11ea-8a2c-91d4bfe60633.PNG)

**Comment by FedeClaudi** [comment]
that's cool!

It sounds like it might be a feature that could be useful for other too, and I wouldn't mind adding a function specific for sharp track integration. 

Would you mind sharing the code you used (or send a PR, as you prefer)? Perhaps also with a sharptrack data set for me to test it with?

thanks, 
Fede

**Comment by tbslv** [comment]
sure, that's no problem. 
I will send you the code and data within the next days!

**Comment by tbslv** [comment]
hey fede, 
I was wondering if there is a fast & easy way to get the coordinates (in ref. space) of any mesh object surface?  From what I've seen most functions only take a single value for x,y &z direction.

**Comment by FedeClaudi** [comment]
Hey, 
All objects in a brainrender scene are instances of vtkplotter [Meshes](https://github.com/marcomusy/vtkplotter/blob/471ae90046f00579d6e4ad894f78a9018564224b/vtkplotter/mesh.py#L62) class (or other similar classes). Therefore you can get the coordinates of all the points that define a mesh's surface using the `Mesh.points()` method.  

`Mesh` also also has a lot of useful methods that you can use e.g. to get the meshe's center of mass or to check if a point is within a meshe's surface. 

I hope this help, but if you needed something else get in touch.

**Comment by tbslv** [comment]
import os
import scipy.io as sio
import numpy as np
from brainrender.scene import *


scene = Scene(jupyter=True) # specify that you want a view from the top

surface = scene._get_structure_mesh('root')
regions= ['VPL']
scene.add_brain_regions(regions, alpha=.4, color='red')

probe_points= sio.loadmat(****path_to_probe_points.mat***)
probe_points =probe_points['pointList'][0][0][0][0][0]
probe_points_df = pd.DataFrame(dict(x=probe_points[:,2]*10,y=probe_points[:,1]*10,z=probe_points[:,0]*10))

scene.add_cells(probe_points_df, color='black', res=12, radius=25)

# 3d linear fit is translated/ adapted from SharpTrack 

r0 = np.mean(probe_points_df.values,axis=0)
xyz = probe_points_df.values-r0
U,S,V =np.linalg.svd(xyz)
direction = V.T[:,0]

# find intersection of linear fit  and surface mesh

p0 = direction*np.array([-1])+r0
p1 = direction*np.array([-15000])+r0 # end point way outside of brain, on probe trajectory though
pts = surface.intersectWithLine(p0,p1)

top_coord = pts[0] 
length = np.sqrt(np.sum((probe_points_df.values[-1] - top_coord)**2))
bottom_coord = top_coord+direction*length

scene.add_vtkactor(Cylinder([top_coord,bottom_coord],r=15,alpha=0.5,c='black'))

scene.render()
``

**Comment by tbslv** [comment]
`
[BrainRenderPackage.zip](https://github.com/BrancoLab/BrainRender/files/4430891/BrainRenderPackage.zip)

`

**Comment by FedeClaudi** [comment]
Awesome, that works perfectly:

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/17436313/78424712-4801ad80-7667-11ea-94b4-fddc9348f302.png">

with ec5b1e694f23f29a08eb2f1abe112a12ac4ac5ba I've added a `Scene.add_probe_from_sharptrack` mostly based on your code, thanks for the contribution!

I will close this issue for now as it has been addressed, but do get in touch if you have other questions!
