### ISSUE TITLE
ModuleNotFoundError: No module named 'vtkplotter'

### ISSUE THREAD

**Issue by neugun** [BrancoLab/BrainRender#47]
Hi!  Nice tool. I am trying to pip install brainrender, but there throw me an error while I running
"import brainrender''
No module named 'No module named 'vtkplotter' After I install 

F:\D\BrainRender\brainrender\__init__.py in <module>
     45
     46 # -------------------------- Set vtkplotter shaders -------------------------- #
---> 47 from vtkplotter import settings
     48 settings.useDepthPeeling = True # necessary for rendering of semitransparent actors
     49 settings.useFXAA = True # necessary for rendering of semitransparent actors
ModuleNotFoundError: No module named 'vtkplotter'

Do I need to install vtkplotter again?
Thank you

**Comment by FedeClaudi** [comment]
hi, 

how did you install brainrender?

If you used `pip install brainrender` it should've installed all the necessary packages, including `vtkplotter`.  

If something went wrong with the installation perhaps try `pip install brainrender --upgrade` or uninstall with `pip uninstall brainrender` and then `pip install brainrender`. 

Please let me know if this doesn't fix the problem.

Thanks, 
Fede

**Comment by neugun** [comment]
Thank for the reply. Yes, I used pip install brainrender many times.  always a error come out: 

Installing collected packages: allensdk, brainrender
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\73110\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\allensdk\\test\\internal\\mouse_connectivity\\test_projection_thumbnail\\__pycache__\\test_visualization_utilities.cpython-37.pyc'

Still trying to figure out why this happens. Thanks!

**Comment by FedeClaudi** [comment]
Hi, 

This second error seems related with the allensdk package. Which also gets installed together with brainrender so there's no need to install it manually. 

Let's try the whole thing to the start so that I can be sure of which steps you've taken. 
I'm assuming that you're using conda to mange your python environments, but let me know if that;s not the case. 

1) Create a new anaconda environment [in conda editor]
```
 conda create -n brainrender python==3.7
 ...
conda activate brainrender
```

2) install brainrender and dependencies
```
pip install brainrender
```

3) install ipython for testing
```
pip install ipython
```

4) test
```
ipython
import brainrender
```

Let me know if you still get an error after this. Also could you please let me know which OS you're using?

**Comment by neugun** [comment]
Thank you!  I am using the windows 10.  I followed the steps you listed and used conda installation.  Everything is good except the last step.  There is a error: can not found vktplotter module. Next I installed the vktplotter mannully, and it doesn't work. So there is nothing wrong of the brainrender installation, but the vktplotter doesn't suit my pc well.  I am trying to solve this and will keep this posted. Thanks!  
![image](https://user-images.githubusercontent.com/26133490/78738344-34ff1e00-7984-11ea-871c-3d0f1b911872.png)

**Comment by FedeClaudi** [comment]
Hi, 

thanks for trying, and sorry it didn't work out. 

If you just try `pip install vtkplotter` what happens? Do you get an error?
If you do `conda list` do you see vtkplotter among the installed packages?

**Comment by neugun** [comment]
Hi! Thanks for your help!  

The vtkplotter requirement already satisfied when I pip install vtkplotter again or check the conda list. But  when I import the brainrender via ipython, a error came out that ModuleNotFoundError: No module named 'vtkplotter'. 

In [1]: import brainrender
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-6d114455d529> in <module>()
----> 1 import brainrender
F:\SW\BrainRender\brainrender\__init__.py in <module>()
     45
     46 # -------------------------- Set vtkplotter shaders -------------------------- #
---> 47 from vtkplotter import settings
     48 settings.useDepthPeeling = True # necessary for rendering of semitransparent actors
     49 settings.useFXAA = True # necessary for rendering of semitransparent actors
ModuleNotFoundError: No module named 'vtkplotter'

**Comment by FedeClaudi** [comment]
hi, that's very weird.. are you sure that the jupyter notebook is using the same anaconda environment you've installed brainrender in? 
If you just try to import vtkplotter do you get the same error?

**Comment by neugun** [comment]
Hi! @FedeClaudi  I realized that it can not work because I typed ipython at the cmd windows.  I built a new enviroment in conda and finnally it worked when I ran it by pycharm.  Thanks so much for the help!!!

**Comment by FedeClaudi** [comment]
Awesome, sorry about all the trouble. 

I hope that it all works smoothly from now on, but do get in touch if you have any problem.
