### ISSUE TITLE
Improved video saving

### ISSUE THREAD

**Issue by FedeClaudi** [BrancoLab/BrainRender#50]
Need to improve how the saving of videos is handled:

1) Use opencv to avoid using ffmpeg
2) Use opencv to support more video formats and codecs

**Comment by FedeClaudi** [comment]
Changed the BasicVideoMaker class (dc04bf001333a45724e6a2d2efee80e3c6b3701a) to support saving with opencv and avoid using vtkplotter's video class. 
Code remains to be tested.

**Comment by youeh1** [comment]
What I did 

1. create a new virtual env
2. pip install brainrender git+https://github.com/BrancoLab/BrainRender.git@animation
3. try to install opencv-python, but it said the module is already installed.
4.  no error while running, but the file came with mp4 instead of avi.
5. the same quality of video.

Thanks!

**Comment by FedeClaudi** [comment]
Excellent, thanks for testing! 
If you want avi you can use the `video_format` argument :)

**Comment by youeh1** [comment]
Sorry for the unclear statement.

Yes, still getting a corrupted video.
I try to use video_format argument, and has no error when I run this.
vmkr.make_video(azimuth=1, niters=360, duration=30, save_name="hong2",video_format="avi")
 
However, a video still comes with mp4, not avi.

Is it correct to use the video_format argument?

Thanks,

**Comment by FedeClaudi** [comment]
Hi, 
yes, that should be the correct argument. Try something like this please:
```
vmkr = BasicVideoMaker(scene, video_format="avi")

vmkr.make_video(azimuth=1, niters=36, fps=5, save_name="test")
```
[passing the video format argument when creating the instance of BasicVideoMaker]

Re the video corrupted in mp4: I'm afraid that that's not a brainrender issue, but something to do with the installation of ffmpeg + necessary codecs.

**Comment by FedeClaudi** [comment]
hi @youeh1  did this help? Are the videos saving correctly now?

**Comment by FedeClaudi** [comment]
This should be fixed for now, so will close. But @youeh1  do get in touch if you still have problems.
