### ISSUE TITLE
Plotter object has no attribute window in video.addFrame()

### ISSUE THREAD

**Issue by FedeClaudi** [BrancoLab/BrainRender#51]
Opening an issue first presented by @jt522 in https://github.com/BrancoLab/BrainRender/issues/45

Error: `Plotter object has no attribute window` in `video.addFrame()` [see original message and screenshot below].

Brainrender and vtkplotter versions:
brainrender 0.3.4.2
vtkplotter 2020.2.3

On MacOS on Jupyter and Spyder 

> Hi,
> 
> Thanks for sharing the fantastic code!
> Let me jump in.
> 
> I have trouble saving a video as well (on Mac and tried Jupyter and Spyder).
> 
> The error I got is shown below.
> Do you have any ideas to solve this problem?
> 
> Thanks,
> 

image
![image](https://user-images.githubusercontent.com/17436313/78828294-66a3d380-79dc-11ea-9c48-8da21854772b.png)

**Comment by FedeClaudi** [comment]
> Do you have any ideas to solve this problem?
The short answer is no, I've never seen this error before. 

If you don't mind, could you send me the code you where using? 
Do you get the same error if you run the example code in `Examples/basic_video_maker.py'?

**Comment by FedeClaudi** [comment]
added on branch animation with dc04bf001333a45724e6a2d2efee80e3c6b3701a
remains to be tested

**Comment by jt522** [comment]
Hi,

Thanks for the quick response.
I got the error because I exit before rendering finishes (by hitting Esc).
Now my problem is same for issue #45.
Thanks for your help.

**Comment by FedeClaudi** [comment]
Hi, oh okay good, I will close this issue then. 

Which of the different problems that where brought up in the thread on issue 45 are you encountering? 

Also I've changed the code for saving video, and should have now fixed all the problems with this aspect of brainrender, but the code needs to be tested. If you'd like to give it a try you can find instructions on how to try the new code here: https://github.com/BrancoLab/BrainRender/issues/45#issuecomment-611199269


I'll close this issue as the original problem was addressed, but feel free to open a new one if you find an issues :)
