### ISSUE TITLE
Loading mesh for just the cerebellum into brain render

### ISSUE THREAD

**Issue by anorak94** [BrancoLab/BrainRender#53]
I have created a mesh of the cerebellum with the corresponding ontology file of the substructures. is it possible to load just the mesh and the corresponding substructures and visualize it using brain render.

**Comment by FedeClaudi** [comment]
hey,

You can use `scene.add_from_file` to load any mesh object in brainrender as long as it's saved as .obj, .stl, .nii or .vtk, see the function definition: 	https://github.com/BrancoLab/BrainRender/blob/13428c6f4535822137984e1204105ae03ce41e01/brainrender/scene.py#L394

If the substructures are also saved as meshes that you can do the same for them. 

And if the meshes are in the same coordinates space as the allen atlas then you can visualise your meshes alongside all the other data types supported by brainrender. 

Hope this helps, 
Fede

**Comment by anorak94** [comment]
thanks
