### ISSUE TITLE
Loading Custom Meshes 

### ISSUE THREAD

**Issue by anorak94** [BrancoLab/BrainRender#55]
I have been trying to load a custom mesh into the brain render 
```

tutorial_scene = Scene(jupyter=True)
actor = tutorial_scene.add_from_file("/Users/ranjak/Downloads/cereb_p4.vtk")
actor.opacity(alpha = 0.3)
actor.smoothLaplacian(niter=100, relaxfact=.0002, edgeAngle=10, featureAngle=60)
actor.rotateX(90, rad=False)
actor.x(0)
actor.y(0)
actor.z(0)
tutorial_scene.add_sphere_at_point( pos=[0, 0, 0], radius=100, color="black", alpha=1)
tutorial_scene.render()

```

doing something like this doesnt help as well

```
root = tutorial_scene.root
actor.rotateX(90, rad=False)
actor.x(0)
actor.y(0)
actor.z(0)
root.x(0)
root.y(0)
root.z(0)

```
This should add both the sphere and the structure at the same position but i get an output like. 
Even when i change the coordinates of the actor using actor.x(newx) etc or rotate it the structures dont overlap or get placed within each other 

<img width="2048" alt="Screenshot 2020-04-25 at 18 52 49" src="https://user-images.githubusercontent.com/45297533/80285638-abdb3b80-8726-11ea-942d-254c9524ff5b.png">

**Comment by FedeClaudi** [comment]
hey, 

Can you try adding this to your code please:


```

tutorial_scene = Scene(jupyter=True)
actor = tutorial_scene.add_from_file("/Users/ranjak/Downloads/cereb_p4.vtk")
actor.opacity(alpha = 0.3)
actor.smoothLaplacian(niter=100, relaxfact=.0002, edgeAngle=10, featureAngle=60)
actor.rotateX(90, rad=False)
actor.x(0)
actor.y(0)
actor.z(0)

# new code starts
com = actor.centerOfMass()
print(f"Actor's center of mass: {com}")
tutorial_scene.add_sphere_at_point( pos=com], radius=100, color="blue", alpha=1)
# end of new code

tutorial_scene.add_sphere_at_point( pos=[0, 0, 0], radius=100, color="black", alpha=1)
tutorial_scene.render()
```

I just want to make sure that there isn't something weird with the bounding box of your actor.

**Comment by anorak94** [comment]
# new code starts
```
com = actor.centerOfMass()
root_com = tutorial_scene.root.centerOfMass()
actor = actor.x(root_com[0])
actor = actor.y(root_com[1])
actor = actor.z(root_com[2])
```

this works for changing the position i think because actor.x(0) actually returns a mesh object so we do an assignment and then back again

i was able to bring them closer how do i fit it inside is there a way to get the coordinates of the cerebellum within the root scene 
<img width="2048" alt="Screenshot 2020-04-26 at 13 35 17" src="https://user-images.githubusercontent.com/45297533/80306305-d2e74b00-87c2-11ea-90a6-c383d6087325.png">

the output of the code you provided is 
<img width="2048" alt="Screenshot 2020-04-26 at 13 37 50" src="https://user-images.githubusercontent.com/45297533/80306390-4e48fc80-87c3-11ea-8c84-3d3c07cd1250.png">

**Comment by FedeClaudi** [comment]
ah nice find, good to know that you can now move it around correctly. 

You can use `scene.get_region_center_of_mass` to get the CoM of the cerebellum, and then move your object there: https://github.com/BrancoLab/BrainRender/blob/74fefa9eefd3bdbd7aef377b016e0f631fb184c2/brainrender/scene.py#L261

It looks like you'll have to rotate the mesh around as well, but that should be easy to do once it's in place.

**Comment by anorak94** [comment]
```
tutorial_scene = Scene(jupyter=True)
actor = tutorial_scene.add_from_file("/Users/ranjak/Downloads/cereb_p4.vtk")
actor.opacity(alpha = 0.3)
actor.smoothLaplacian(niter=100, relaxfact=.0002, edgeAngle=10, featureAngle=60)

com = actor.centerOfMass()
p1, p2, p3 = tutorial_scene.get_region_CenterOfMass("CB", unilateral=False, hemisphere="right")
print(f"Actor's center of mass: {com}")
print (f"Root's center of mass: {p1, p2, p3}")
actor = actor.pos(p1+9000, p2+3000, p2-2000)

p1_n, p2_n, p3_n = actor.centerOfMass()
print (f"New center of mass : {p1_n, p2_n, p3_n}")

tutorial_scene.add_sphere_at_point( pos=[p1_n, p2_n, p3_n], radius=100, color="blue", alpha=1)


tutorial_scene.add_sphere_at_point( pos=[p1, p2, p3], radius=100, color="blue", alpha=1)
tutorial_scene.add_sphere_at_point( pos=[0, 0, 0], radius=100, color="black", alpha=1)
tutorial_scene.render()
```

it kind of works but its strange that actor.pos(x1, y1, z1 ) doesnt position according to the center of mass but by some other maybe bounding box kind of logic but my mesh fits inside its smaller than the root brain probably have to scale it up etc but thanks if you can suggest any other cosmetic changes to make it look better that would be nice because my mesh looks ugly and the allen brain ones look much nicer, but the tool looks really amazing thanks a lot 
<img width="2048" alt="Screenshot 2020-04-26 at 15 01 59" src="https://user-images.githubusercontent.com/45297533/80308415-34adb200-87cf-11ea-898a-5c5e052c5a1a.png">

**Comment by FedeClaudi** [comment]
yeah there might be some issue with how you created the mesh which causes the CoM not to be where you'd expect. 

You can try smoothing the actor + change color and transparency to make it look better. You can also try playing around with the actor's material to change how it reflects light.

**Comment by anorak94** [comment]
thanks

**Comment by anorak94** [comment]
is there a way to define a new region like i want to overwrite the "CB" region in the brain render with my own mesh region so that i get points inside the new mesh and not the old one

**Comment by FedeClaudi** [comment]
I'm afraid not. Brainrender relies on the Allen institute's SDK to interact with the Allen brain atlas. All parts of brainrender where you can specify the name of the brain region directly depend on that and can't be easily changed. 

But once you have your brain region rendered as an actor you should be able to do all the same as what the other functions are doing. 
What is it that you want to do exactly?

**Comment by anorak94** [comment]
i want to add other brain regions which are subregions of the cerebellum and extend the existing functionalities of brain render to those new regions and have an ontology tree etc basically everything that is in the brain render for the adult p56 mice but for different ages

**Comment by FedeClaudi** [comment]
I see, cool!

It would take a bit of work but we can work on it, it'd be nice to have. 
I think maybe @adamltyson  you did something like this before?

**Comment by adamltyson** [comment]
It was something I was looking into - how we could support arbitrary atlases in brainrender. 

However, I didn't get any further than just getting brain regions from an image-based atlas, extracting the surface and displaying in BR.

**Comment by FedeClaudi** [comment]
Okay, thanks!

One way would be for functions like this: https://github.com/BrancoLab/BrainRender/blob/74fefa9eefd3bdbd7aef377b016e0f631fb184c2/brainrender/scene.py#L261

To not just accept regions acronyms from the Allen atlas, but also to work on custom meshes. 

This wouldn't fully achieve the goal of supporting a custom atlas, but would extend some of brainrender's functionality to custom meshes.

**Comment by FedeClaudi** [comment]
Move the conversation here: https://github.com/BrancoLab/BrainRender/issues/56
