### ISSUE TITLE
Support for custom atlases

### ISSUE THREAD

**Issue by FedeClaudi** [BrancoLab/BrainRender#56]
Some users manifested interest in using brainrender with atlases other than the Allen Brain atlas. 

While any 3d mesh can be rendered in brainrender with: https://github.com/BrancoLab/BrainRender/blob/74fefa9eefd3bdbd7aef377b016e0f631fb184c2/brainrender/scene.py#L394

many functions only work for the Allen atlas because they expect a region's acronym as input: 
https://github.com/BrancoLab/BrainRender/blob/74fefa9eefd3bdbd7aef377b016e0f631fb184c2/brainrender/scene.py#L428

A first workaround would be to let these function accept filepaths to custom meshes or vtkactors as argument, then most of brainrender's functionality would be working on a custom atlas. 
However, a more comprehensive and long term solution would be preferable.

**Comment by FedeClaudi** [comment]
Some of brainrender's functionality depends on external APIs and databases (e.g. mouselight). 

In this case it would be hard to use custom atlases, and even if it were possible it might cause problems since the data are registered to the Allen atlas. 

So functionality that depends on datasets based on the Allen atlas will probably not be extended.

**Comment by adamltyson** [comment]
Do you mean "functionality that depends on datasets **not** based on the Allen atlas will probably not be extended."?

Steve and I were playing with [this atlas](https://www.nature.com/articles/s41467-019-13057-w). It's based on the ARA (and is registered to it), but has greater granularity. We had a prototype working in cellfinder which used an image-based atlas and an amended `structures.csv`. We could then extract regions and render as surfaces in BR as needed.

**Just thinking out loud:**
I've had success with [GIN}(https://gin.g-node.org/cellfinder) for hosting data (and allowing automatic downloads when needed), so I think if someone were keen to persue this, the steps would be:
* Extract surfaces for every brain region from an image-based atlas (if the surfaces didn't already exist)
* Ensure metadata for hierachy etc. exists
* Host online in a standardised way
* Edit BR in such a way that it could query this downloaded atlas, rather than the Allen API

Is there any reason why this approach shouldn't work for other (non ARA based) atlases?

**Comment by FedeClaudi** [comment]
So I think that there are two cases:

1.  Atlases that are extensions of the Allen atlas for the adult mouse brain. 
2. Atlases that are very different (e.g. different species or developmental stages, or specific to a brain structure).

For the first case datasets like mouselight would be okay, since it's roughly the same brain.
What I meant is that in the more general case datasets based on ARA should not be used with other atlases (obviously). 

I like your approach, though I guess steps 1 -> 3 should happen outside of brainrender. Then brainrender can download/load the data and organize an atlas.

**Comment by adamltyson** [comment]
Yeah sounds good. 1-3 should definitely happen outside of BR, but there should be some standardized structure (that could maybe also be used with amap and cellfinder).

**Comment by FedeClaudi** [comment]
Yeah, agreed that would be good. 

I think for now I want to deal with the easier case of pre-existing and established atlases (e.g. drosophila's) as:

1.  These atlases would probably be relevant to a larger number of people
2. They are already available and hopefully accessible to anyone

Once brainrender can be used with these atlases it should be easy(er) to support custom user-created atlases too.

**Comment by adamltyson** [comment]
Great. Keep me in the loop, I'd like to see how they could be supported with amap/cellfinder/neuro etc too.

**Comment by FedeClaudi** [comment]
Sure, I first need to get a hold onto these atlases, do you know where to find them?

I've created a new branch to work on this, if you want to keep an eye on it.

**Comment by adamltyson** [comment]
There are some [here](https://scalablebrainatlas.incf.org/index.php), but they're pretty low-res.

If you're interested in zebrafish etc. I can ask around my old dev neuro department.

**Comment by anorak94** [comment]
just a few comments @adamltyson mentions that we can "Extract surfaces for every brain region from an image-based atlas (if the surfaces didn't already exist)" does this mean that the image based atlas already has meshes generated for it because i couldnt find any the way i am doing it is getting a neuroanatomist to draw the structures in svg file, parsing those files and then registering it to a reference atlas(which i create), transferring the annotations to itk snap and then interpolating labels followed by manual editing to get the entire mesh for the structures. I also had to write the code for the volumetric brain creation from histological stacks and mri priors i used @stanva excellent antspy for it. Do you guys know of an easier way to get around this process this is roughly what the allen brain did for their atlas creation but my meshes look really ugly

**Comment by FedeClaudi** [comment]
I'll let Adam explain this more in detail but in the meanwhile you can have a look here:

https://github.com/BrancoLab/BrainRender/blob/c6c4fdb740564b2b762e1aa91eb83256c33c9720/brainrender/Utils/image.py#L53

and here (though Neuro is still under development):
https://github.com/SainsburyWellcomeCentre/neuro/tree/master/neuro/segmentation/manual_region_segmentation

**Comment by anorak94** [comment]
So the way to use this function would be to create a mask of the different regions of the cerebellum using manual delineations in histological space i then transfer these to the reference atlas and use this function to create a mesh of the surface i do this for a lot of serial images and simply stack them to get the 3d mesh.?

**Comment by adamltyson** [comment]
I'm not sure if I fully understand, but I'll try to help clarify what tools we have:

- Brainrender uses the Allen adult mouse atlas, which is defined both as images (each region has a value), and meshes (which brainrender downloads and renders).
- We have used other atlases based on the Allen (e.g. https://www.nature.com/articles/s41467-019-13057-w) which are still in the same coordinate space, but with different labels. We have used the image based atlas to extract meshes for brain regions, and display them manually in brainrender.
- We are developing tools in [neuro](https://github.com/SainsburyWellcomeCentre/neuro) to allow people to manually create their own meshes (they just draw round a region in 3D. Some of this code is also still in brainrender, but maybe should be removed (@FedeClaudi?).

So I don't think we have tools to do what you want to do, but there is maybe some code that can be reused. Happy to work with you if you wanted to make a PR to neuro to add functionality etc.

**Comment by FedeClaudi** [comment]
Hey but I think what he meant is that you need a 3D mask for each brain region to use the marching cube stuff and extract the surface's mesh. If that's what you meant @anorak94  that's correct, you need a mask for each brain region defined in the same coordinate space as the atlas. 

What we don't have is a way to create these masks though. 

And yes @adamltyson that code will be removed soon enough :)

**Comment by anorak94** [comment]
@FedeClaudi i have a way to extract those regions from svg allen brain atlases or other svg delineated images

**Comment by FedeClaudi** [comment]
I see, I'm afraid that's something that we don't have tools for at the moment, sorry

**Comment by vigji** [comment]
Hi @FedeClaudi!
With @adamltyson in the last days we were thinking about some way of having a nice API  for dealing with an Atlas representation, defined as a folder with some stacks, regions, metadata, some link for download, etc. I temptatively put a draft for it in the neuro package, I am sure there would be a loot of overlapping for stuff that you already might have or would need for this support of general atlases - what about try to come out with a common solution for dealing with it there or in some other place we can all refer to?

**Comment by vigji** [comment]
The good practice of posting this before having read all the above messages fro @adamltyson and read you Atlas class code 😅 
The point about discussing a multipurpose Atlas class in some module more general than `brainrender` holds though!

**Comment by FedeClaudi** [comment]
hey, yeah that sounds great! I'd be happy to work on it with you guys. I guess it would have to come with a solution for hosting data for atlases that don't have an API like the Allen atlas?

I started doing something similar for brainrender:  https://github.com/BrancoLab/BrainRender/blob/custom_atlases/brainrender/atlases/base.py 

For just brain render's needs this is enough, but it would for sure be good to have something standardised across packages. 

Do you guys think that it should be part of neuro or should it be it's own thing?

**Comment by adamltyson** [comment]
Hi both,

I think hosting should be fine ([GIN has worked well for me so far](https://gin.g-node.org/cellfinder)), we just need a standardised structure.

I vote for a new repo, as it shouldn't have many dependencies, and neuro has some fairly heavy ones now.

**Comment by vigji** [comment]
I also vote for a new one, so we start with a fresh mind and add only things as we see them suited :)

**Comment by FedeClaudi** [comment]
allright, sounds great, I'm happy to be part of it!

**Comment by vigji** [comment]
Great!
I am for sure more of a newcomer to the brain atlases enterprise than you; I have tried to look around for something like this already existing and I could not find anything obvious existing in this general form. Does the Allen actually provide something like a general API to deal with their atlas data that we would be overlapping with?

For hosting, should I make a new organisation so that we all have admin access?

**Comment by FedeClaudi** [comment]
No I'm afraid the Allen's SDK are specific to their stuff.

**Comment by adamltyson** [comment]
Yeah new organisation is a good idea. Any ideas for a name (clearly the most important thing)?

For a package name - `atlases` is available on pypi

**Comment by vigji** [comment]
Something fancier? :D `brainglobe`? `brainchart`? 😃

**Comment by adamltyson** [comment]
I like both of those. Do you mind making an org, then we can discuss code organisation and what packages we would need?

**Comment by vigji** [comment]
Sure!

**Comment by FedeClaudi** [comment]
@anorak you can check [this](https://github.com/BrancoLab/BrainRender/blob/master/Docs/custom_atlases.md) to see how you can start using brainrender with custom atlases while vigji Adam and I work on brainglobe.

If you plant to do so, make sure to get the latest code with
```
pip install -U git+https://github.com/BrancoLab/BrainRender.git
```

**Comment by anorak94** [comment]
hey thanks it looks cool

**Comment by FedeClaudi** [comment]
Hey @anorak94  we've made some progress with brainglobe and we start having more and more atlases supported. 

One of the problems we've encountered is that when we create new meshes in our atlases they have some imperfections. I know that you've had the [same problem before](https://community.brain-map.org/t/creating-meshes-from-volumetric-data/509/2) and was wandering have found a solution?

**Comment by anorak94** [comment]
What kind of imperfections do you mean. Id be happy to help. I asked a question on the allen brain forum about how they create meshes for their atlases. Maybe you can take a look at that as well. The guy suggested doing decimation for reducing mesh sizes and some structure shrinkage to ensure that the meshes of different structures dont intersect each other. 

Apart from that. I have written code which extracts contours from svg images overlays them on mri atlases then does interpolation to propagate labels to the intermediate slices(this step is buggy and the main source of errors in my meshes) i then load the segmentation masks in itk snap and do an export mesh. In itk snap i also do some manual editing to ensure that the structires are well delineated. I then smooth the meshes. 

If you can tell me what imperfections you have in your meshes maybe i could tell you more. 

Best

**Comment by FedeClaudi** [comment]
That's great, thanks for the help. 

We are working with 3d images so the first part of the workflow is different. 
We have a 3d mask with the voxels assigned to a brain region, and we extract a mesh with the surface of the mask. However these often look blocky and sometimes they have artifacts (e.g. some geometry under the brain region's surface), so we are looking for ideas on how to clean them up. 

I think we will try to implement what was suggested to you [here](https://community.brain-map.org/t/creating-meshes-from-volumetric-data/509/2), but were wandering if you had any further info that would help. 

By the way, I know that you were working on creating an atlas (was it a developmental mouse atlas?), if you want to develop it as part of brainglobe / have it supported by brainglobe we welcome anyone interested in helping developing the atlas api.

**Comment by anorak94** [comment]
hey yeah indeed i was working on creating an atlas for the developmental mouse brain. i have written code for creation of a 3d reference volume from histological stack(rn im waiting for some mri data from developing mouse brain to test it, it works on the adult mouse brain i used the pre built 3d volume as a proxy for the mri data). i then wrote scripts for getting meshes from volumetric data(so i neuroanatomists will draw on the reconstructed atlas in step 1 i will transfer these annotations to the reference atlas and then extract the meshes). Thus creating a fully annotated allen brain atlas for every age of the mouse brain (given a histological stack, an mri volume and a neuroanatomist willing to draw structures). i have tested parts of the pipeline individually but i havent run it all together at once and created a final mesh i dont have the mri data to do it. i would be happy to share my code and everything else i just wanted to see it work end to end for once(we have tried to arrange some data and hopefully we should get it soon dont know when but if my pipeline works id be happy to share it , just need to ask my PI).

**Comment by FedeClaudi** [comment]
That sound cool, let us know when you get it to work and we can integrate it with brainglobe so that it's fully supported by software like cellfinder and brainrender
