### ISSUE TITLE
Help figuring out how to use Scene.add_cells_from_file 

### ISSUE THREAD

**Issue by pllorach** [BrancoLab/BrainRender#63]
Hi, I have recently started using brainrender and went through the tutorial. I am looking forward to using it to render our own data, but I am having trouble figuring out how to use the Scene.add_cells_from_file line. I have a .csv file with coordinates for active neurons that I would like to render. I have tried to edit the scene script to specify the path of the .csv file but I have not been successful, and I am only rendering a blank brain when doing so.

Does anyone have any advice as to how I can correctly use Scene.add_cells_from_file? Any help would be greatly appreciated! 
Thank you

**Comment by FedeClaudi** [comment]
Hi, thanks for getting in touch. 

It would be easier to help if you shared more details like the code you're using, which brainrender version etc..

Are you getting any error or warning message when you try adding cells? Or it just doesn't do anything?

How's you .csv file organized? 
Brainrender assumes that your .csv has three columns: `x`, `y`, `z` that specify the location of each cell. If that's not the case and your columns have a different name you can try loading the cell coordinates from the file first, changing the column names and then adding the cells to the scene. something like:

```
import pandas as pd
from brainrender.scene import Scene

cells = pd.read_csv('pathtofile')
cells.columns = ['x', 'y', 'z']

scene = Scene(title='My cells')
scene.add_cells(cells)
scene.render()
```
Hope this helps

**Comment by pllorach** [comment]
Hi Federico,

Thanks for getting back so quickly! I am new to programming so I was not sure how to write the code to include our own data, and when I tried myself I would not get any errors, it just rendered a blank brain without loading my data. 

However, trying the script your sent and using cells = pd.read_csv('pathtofile') worked and I was able to render our data! However, since we used ClearMap to analyze the data, we ran into a similar problem as in [issue 38](https://github.com/BrancoLab/BrainRender/issues/38), where our data is not aligned with the brain. 

I think we can close this issue and I will closely follow the progress from issue 38, to implement the solution once fixed!

Thank you very much for your help! It's greatly appreciated

**Comment by FedeClaudi** [comment]
Great, thanks for letting me know that the solution worked. 

If you have any other question get in touch, and hopefully we will be able to fix the problem with clearmap data in the near future.

**Comment by pllorach** [comment]
Hello again, 

I have been attempting to scale our .csv file to align with the brain in the scene to see if I could get a first image. I attempted a few different lines of code, and used examples provided from [this issue](https://github.com/BrancoLab/BrainRender/issues/54#issuecomment-615886293) but am not getting any luck. Do you know of similar code I could use to transform the x, y and z coordinates? Here is the code I have been using:

> import sys
> sys.path.append('../') 
> import os
> import pandas as pd
> from vtkplotter import *
> from brainrender import *
> from brainrender.scene import Scene
> from brainrender.Utils.data_io import listdir
> scene = Scene()
> cells = scene.add_cells_from_file("C:/Users/Pierre/Desktop/Lab/data_2.csv")
> scene.render()

This renders our data, but it is not aligned with the sample brain. I attempted to do the following manipulations, which I believe could have failed as I do not have a .vtk file per the example I followed. The end of the code I tried was the following:

>scene = Scene()
>cells = scene.add_cells_from_file("C:/Users/Pierre/Desktop/Lab/data_2.csv")
>cells.Scale(2,1,1) # make it twice as large along one direction
>cells.rotateX(90) # rotate by 90 degrees along x axis
>cells.translate(np.array([100, 0, 0]) # move by 100 in one direction
>scene.render()

The errors I got back were the following- 

>cells.Scale(2,1,1)

>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'Scale'

> cells.rotateX(90)

>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'rotateX'

>cells.translate(np.array([100, 0, 0])

>>...

After this, python stays at this step and just has ... displayed.

I was able to do some of these manually by scaling the original data, and got a close overlap, but I would rather not do it that way and risk introducing errors. Do you know how I can modify the code to work with .csv files to adjust the data to fit the brain in the scene? I was not able to find documentation online on how I could do this. If you do not know, I can wait until a solution is found for data created using ClearMap.

Let me know if I can help by providing further information,
Thank you for your time and help!

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for getting in touch. 

The error `AttributeError: 'NoneType' object has no attribute 'Scale'` is my fault. `Scene.add_cells_from_files` doesn't return anything at the moment, so your `cells` variable is actually `None`. I will fix this soon (https://github.com/BrancoLab/BrainRender/issues/69). 

In the meanwhile you can two one of two things
1) Load cells with `pandas` and use `Scene.add_cells` which does return the `mesh` object:

```
coords = pd.read_csv('filepath')

scene = Scene()
cells = scene.add_cells(coords)


# move cells around

scene.render()
```

Though given that `Scene.add_cells` creates the `cells` `mesh` with `vtkplotter.shapes.Spheres`, I think that if you start scaling and rotating the entire mesh you'll get some funky results. 

It might be better to act directly on the coordinates by doing something like this:
```
coords['x'] += 100
```

If you want to send me the .csv file I can play around with this and see how to best fix it.

**Comment by adamltyson** [comment]
Just to chime in, if you can share the output from clearmap, we can look into it. cc @sgoldenlab

**Comment by FedeClaudi** [comment]
Hi @pllorach thanks for sending me the .csv file by email. I'm replying here to keep everyone in the loop. 

I've played around with aligning your data.
Here's how to do it using vtkplotter's `Mesh` methods (you could also do things on the raw coordinates data as you did in the code you sent me, just rotation might easier using actors directly):

```
import pandas as pd
import numpy as np
from vtkplotter import *

import brainrender

from brainrender.scene import Scene

from brainrender.Utils.data_io import listdir

 

coords = pd.read_csv("data_test.csv")


brainrender.SHOW_AXES = True # makes it easier to see how to move stuff
scene = Scene()

cells = scene.add_cells(coords, color_by_region=False, radius=.5, alpha=.25)

# Center cells and root
cells_pos = cells.centerOfMass()
cells.pos(cells_pos)
root_pos = scene.root.centerOfMass()
cells.pos(root_pos)


# Scale and rotate cells
# After scaling the position of the cells will not be centered on the root anymore
cells.scale([30, 27, 25]).rotateX(90)

# Center
cells.x(root_pos[0] + root_pos[0]-cells.centerOfMass()[0])
cells.y(root_pos[1] - root_pos[1]-cells.centerOfMass()[1])
cells.z(root_pos[2] + root_pos[2]-cells.centerOfMass()[2])


# Fine tune position
cells.y(cells.y()-2000)
cells.x(cells.x()-750)
cells.z(cells.z()+500)


# render


scene.render()
```

I haven't fine tuned the values, but you should be able to do that to get a decent fit
![image](https://user-images.githubusercontent.com/17436313/81666089-75e1cb00-9439-11ea-8298-196f42372f55.png)


It's a bit tedious to adjust the values until you get the best fit, but if the offsets are the same for all data it should be okay. The main issue is that obviously the results will never be perfectly aligned.

**Comment by marcomusy** [comment]
@FedeClaudi I see you're becoming a vtkplotter expert :)

I can only add a piece of advice: you can use `mesh.origin(x,y,z)` to make scaling and rotations operate around a shifted point.
Also you can use the shortcut `cells.addPos(-750,-2000,500)`.

you can see how it works in this example:
```python
from vtkplotter import *

b = load(datadir+'teapot.vtk')
b.pos(1,2,3)
# b.origin(-1,-2,-3)
# b.scale(0.5)
show(b, Point(), 
     'CM is '+precision(b.centerOfMass(),3),
     axes=1)
```

**Comment by FedeClaudi** [comment]
`mesh.origin(x,y,z)` ! that's what I was looking for, I thought that setting `mesh.pos` would be doing the same, but obviously it's origin, that should make all rotation and scaling operations much easier :)

One question, why is `mesh.pos` not the same as `mesh.origin` nor `mesh.centerOfMass`?

**Comment by marcomusy** [comment]
> One question, why is `mesh.pos` not the same as `mesh.origin` nor `mesh.centerOfMass`?

this is a bit tricky in VTK but it makes sense if you think that one may need to disentangle an object position from the way it should scale, and centerOfMass is also a different thing as it very much depends on the distribution of the vertices of the mesh in space.

**Comment by FedeClaudi** [comment]
cool, thanks!

@pllorach  here's the updated code taking into account Marco's suggestions:
```

coords = pd.read_csv("data_test.csv")


brainrender.SHOW_AXES = True # makes it easier to see how to move stuff
scene = Scene(add_root=True)

cells = scene.add_cells(coords, color_by_region=False, radius=.5, alpha=.25)


# Set the origin of cells
bounds = cells.bounds()
cells.origin(np.mean(bounds[0:2]), np.mean(bounds[2:4]), np.mean(bounds[4:]))


# Scale and rotate
cells.scale([30, 27, 25]).rotateX(90)


# Move to root
cells_pos = cells.centerOfMass()
cells.pos(cells_pos)
root_pos = scene.root.centerOfMass()
cells.pos(root_pos)

# Fine tuning
cells.addPos(-1800, 0, 2000)


scene.render()
```

**Comment by pllorach** [comment]
Hi all,

Thanks for all the help, this is incredibly helpful! 
I attempted both of the scripts you updated but I keep getting an error for some of the steps. I am not sure if I am missing a module or not but I updated brainrender just in case I was missing something. 

The error I receive is the following- 
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'bounds'
```
This took place for a few lines and I got the same error through the script, with the no attribute '####' changing based on the line I ran. 
I received this error for 'origin', 'scale', 'rotate', 'centerOfMass', 'pos' and 'addPos' from the last updated script you sent.
From the first script you sent after you received the .csv file, I received that same error for 'centerOfMass', 'pos' 'scale' 'x', 'y', 'z'.

Additionally, I do not get an error when doing `brainrender.SHOW_AXIS = True`, but the rendered scene does not include the axis.

I'm not sure if I am missing anything in my packages, as I mentioned, I updated brainrender in case I was missing anything. I am on Windows 10, using Python 3.7.7, Pandas 0.25.3, vtk 8.1.2, numpy 1.18.4.
Do you have some idea as to why I get this specific error and what I could do to fix it moving forward? Thanks everyone for your help and time!


@adamltyson I shared the .csv file with Federico via email, but let me know if you need additional files for testing!

**Comment by FedeClaudi** [comment]
Hi, 

I've made some changes to brainrender that will have fixed these issues, but I haven't published it yet so you will need to update brainrender directly from the github repo with:

``` pip install -U git+https://github.com/BrancoLab/BrainRender ```

Let me know how it looks after doing that.

**Comment by pllorach** [comment]
Amazing:) Thank you Federico, it's working great! 
I will keep testing this out with our data and if I have any further questions I will reach out. If you need any help with testing clearmap outputs in brainrender, let us know!

**Comment by FedeClaudi** [comment]
awesome, get in touch for any other issue!

**Comment by sgoldenlab** [comment]
Hi All, @pllorach 

Apologies, totally missed this convo when it happened! Just to close it out on our end, and for anyone else trying to visualize ClearMap data, what ended up being the best scaling and rotation values to align CM segmented cells to Brainrender?

Thanks!

**Comment by pllorach** [comment]
Hello @sgoldenlab!

For each sample I attempt to visualize in Brainrender, it seems I need to use slightly different cell positions for the sample to line up properly. 

Here is an example of the settings I use for one of the samples -

```
bounds = cells.bounds()
cells.origin(np.mean(bounds[0:2]), np.mean(bounds[2:4]), np.mean(bounds[4:]))
cells.scale([26, 26, 26]).rotateZ(-90)
cells_pos = cells.centerOfMass()
cells.pos(cells_pos)
root_pos = scene.root.centerOfMass()
cells.pos(root_pos)


cells.addPos(-600, -800, 2450)
```

Some settings that are consistent across samples are the scaling (26 for x, y, z works well for our data), and rotation of the Z axis by -90. We've had to do slight changes to  `cells.addPos()` to align the data, but it's not perfect yet, I am still testing different settings. 
I hope this is helpful and you can render your data!

Do we have any idea as to why these settings might need to be updated from sample to sample? Does it have to do with how the image was processed, or how the data was output?

Thanks all for the help, and I hope the above settings are useful. Let me know if you have further questions!
