### ISSUE TITLE
BUG: brainrender.BACKGROUND_COLOR not working

### ISSUE THREAD

**Issue by FedeClaudi** [BrancoLab/BrainRender#66]
**Describe the bug**
Changing
```
brainrender.BACKGROUND_COLOR
```
should change a scene's background but it doesn't seem to be working. 
After a quick inspection it looks like it broke with recent upgrading of vtkplotter, but need to figure out how to fix it.

**Comment by marcomusy** [comment]
yup... i'm the guilty one.. i slightly changed its behavior.. what if you pass that variable to the show() command show(bg=brainrender.BACKGROUND_COLOR)

**Comment by FedeClaudi** [comment]
hey that works! Thanks for checking in ;)
