### ISSUE TITLE
Consider pruning your git history

### ISSUE THREAD

**Issue by paulbrodersen** [BrancoLab/BrainRender#74]
**Is your feature request related to a problem? Please describe.**

I just tried to clone your git repository unsuccessfully. 

```shell
128 paul@paul-XPS-15-9560:~/src$ git clone https://github.com/BrancoLab/BrainRender.git
Cloning into 'BrainRender'...
remote: Enumerating objects: 263, done.
remote: Counting objects: 100% (263/263), done.
remote: Compressing objects: 100% (183/183), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

There are [several potential reasons for this issue](https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls).

I suspect that in my case, my ISP is actually to blame for timing out the connection prematurely. 
Masking my traffic by connecting to a VPN solves the issue. 

**Describe the solution you'd like**

Not everybody has access to a VPN to work around their stingy ISP. This issue could be prevented by reducing the size of the repository. 

![Screenshot from 2020-05-26 12-07-43](https://user-images.githubusercontent.com/8046146/82894943-52e00c80-9f4b-11ea-9eb8-d5ace00dde69.png)

As ~80% of your repository size is in your git history, [pruning your git history](https://stackoverflow.com/questions/2116778/reduce-git-repository-size) might be the most efficient (and least impactful) way to go about it.

**Additional context**

**Comment by FedeClaudi** [comment]
Thanks for the advice, I had no idea. 

I tried what you've suggested above, but it didn't make a change. I then tried some other stuff and manged to delete the entire repo's history (do you know how to restore it?), but `/.git` is still 233M. Do you know what else I could try to clean things up?

**Comment by FedeClaudi** [comment]
I've manged to fix the history :) 

`/.git` is still large though...

**Comment by paulbrodersen** [comment]
Unfortunately, it has been many years since I had to do anything similar so I don't remember what exactly I did back then to get rid of old versions of media files, etc. Nowadays, github and bitbucket seem to recommend both this 3rd party tool: https://rtyley.github.io/bfg-repo-cleaner/ However, I have never used it myself, so I can't comment on how effective it will be.
