### ISSUE TITLE
Integration with brainglobe atlas API

### ISSUE THREAD

**Issue by FedeClaudi** [BrancoLab/BrainRender#76]
@vigji

I've started the integration of brainrender and brainglobe api, let's develop this in a [branch](https://github.com/BrancoLab/BrainRender/tree/brainglobeintegration) until it's mature enough for merging.

This is where I started doing stuff: https://github.com/BrancoLab/BrainRender/blob/brainglobeintegration/brainrender/atlases/brainglobe.py

I think that the idea is going to be to have a `BrainGlobeAtlas` which implements most of the methods of (brainrender's) base `Atlas` class needed to populate a scene. 

Then individual brainglobe atlases are supported by a dedicated class (e.g. `BGFishAtlas`) which brings both things together. These classes won't be implementing anything directly, unless they need to do something unusual like getting streamlines and tractography data for ABA. 

Does the general structure make sense to you? I'm having a hard time finding a cleaner way

**Comment by vigji** [comment]
Yep, right now it looks like the cleaner solution to me as well! Let's see if the results are good :)

**Comment by FedeClaudi** [comment]
Cool, I'll start moving code from brainrender Atlas to brainglobe Atlas, hopefully this will make things a bit cleaner still. 

For the zebrafish atlas for now it's just brain regions right? Or is there an API to get neural morphologies? If so it'd be good to put it together with `morphapi` in brainglobe.

**Comment by vigji** [comment]
Currently there's no API that I am aware of but is probably on its way/potentially implementable as they have a bunch of neuronal tracing data together with the atlas on the website.
However, I have a bunch of local data already morphed in that coordinates space that I would like to explore with our tools, so I guess I should have a look at `morphapi` for integrating that in the visualisation? :)

**Comment by FedeClaudi** [comment]
I've changed things slightly and updated `ABA` to work with `BrainGlobeAtlas`.
there's still a bit of redundant code across the different packages but it's getting there. 

I haven't moved methods like `get_neurons` out, but I took some out of the code that deals with boring stuff like parsing the color arguments out of the class declaration, hopefully making it more concise.
