### ISSUE TITLE
MATLAB GUI equivalent

### ISSUE THREAD

**Issue by Yaoyao-Hao** [BrancoLab/BrainRender#77]
Hi,
I just want to leave you a message that I developed a Matlab equivalent (BrainMesh) with Graphical User Interface (GUI) to render the brain structures. Hope that will help people who only use Matlab or even do not program. Could you help to broadcast the tool link (https://github.com/Yaoyao-Hao/BrainMesh) in your README file? Thanks a lot.

Best,
Yaoyao

**Comment by FedeClaudi** [comment]
Nice one! Adding it now.
