### ISSUE TITLE
upgrading to vedo

### ISSUE THREAD

**Issue by marcomusy** [BrancoLab/BrainRender#79]
As you may have noticed vtkplotter moved to `vedo`.

`vtkplotter 2020.3.1` and `vedo 2020.3.2` are in `pip` and are equivalent.

Let me know if you encounter any issue in the transition.

**Comment by FedeClaudi** [comment]
Hi Marco, 

Thanks for letting me know, is it just a name change or is there any functional difference?
I will update `setup.py` in the development branch.

**Comment by marcomusy** [comment]
it's name change + various bug fixes, one of these is the `obj` writing to file, which if i remember was used by brainrender,
the rest are developments on tet meshes which are probably not relevant.

**Comment by FedeClaudi** [comment]
I see, okay thanks for the heads up :)
