### ISSUE TITLE
Feature: Don't use print statements for warnings to the user.

### ISSUE THREAD

**Issue by adamltyson** [BrancoLab/BrainRender#82]
**Is your feature request related to a problem? Please describe.**
Could any information to the user (like the statement below that's printed to the console when brainrender is imported) use the warnings or logging module rather that being printed? That way they can be suppressed when using brainrender as a dependency?

`screenshots are set to have transparent background set the parameter "SCREENSHOT_TRANSPARENT_BACKGROUND" to false if you would prefer a not transparent background`

**Describe the solution you'd like**
Any statements like this to be "suppressible" in some way (like warnings can be filtered).

**Additional context**
When using brainrender with [cellfinder](https://github.com/SainsburyWellcomeCentre/cellfinder), some users are confused (because there's no documentation of taking screenshots in cellfinder).

I don't mind the method, but I do like using the logging module.

Thanks Fede!

**Comment by FedeClaudi** [comment]
Makes a lot of sense...  also the message should clearly say that it's a brainrender problem I guess. 

Would a warning be okay for you?

**Comment by adamltyson** [comment]
Yep that's fine, they're easy to supress.

P.S. The message is missing a space (`to have transparent backgroundset the parameter`).

**Comment by FedeClaudi** [comment]
Thanks. 

I've made this change (5dde6b403a8eef50fd7ccef258ff398b29c2b1a3) in the brainglobe integration branch as that's were I've been developing stuff, but it's not released yet. I hope it will be by the end of the week (depending on brainglobe itself and vedo's release). 

If you need this soon I can change it on master as well and publish a sub-version for pip install

**Comment by adamltyson** [comment]
> If you need this soon I can change it on master as well and publish a sub-version for pip install 

No rush at all, thanks!
