### ISSUE TITLE
BUG all bgatlas stacks loaded on instantiation

### ISSUE THREAD

**Issue by vigji** [BrancoLab/BrainRender#85]
For the brainglobe integrations, this

https://github.com/BrancoLab/BrainRender/blob/99e986239a291c9dfd64da766485f7870c398dad/brainrender/atlases/brainglobe.py#L339

Seems to be suboptimal as it ask to load all the stacks before they are actually used. Is it necessary in BrainRender? 

If you are subclassing, such syntax should not be necessary as all properties will be inherited.

**Comment by FedeClaudi** [comment]
I might explicitly ignore the stacks, that's a good idea. 

The reason why that is the way it is, is that I need to subclass `BrainGlobeAtlasBase` and whatever class represents the atlas from brainglobe. That's because `BrainGlobeAtlasBase` is necessary to ensure functionality necessary for brainrender. 

I could define a bunch of classes, one for each class defined in `brainatlas_api.bg_atlas`, but I wanted something were I can create these classes on the fly so as not to risk falling behind with brainatlas. 

As it stands `BrainGlobeAtlas` subclasses `BrainGlobeAtlasBase` and explicitly inherits the methods and attributes of whatever is passed as `atlas` to `__init__`. I tried alternatives like:
```
atlas.__init__(self)
super(atlas, self).__init__()
```

and a couple other things but they all gave errors... if you know of an easier way to do something like this that would be great!

**Comment by vigji** [comment]
Sorry, ok, no, you are not subclassing, but it feels strange that you pass an atlas to an atlas class and then set all its attributes, that's basically a way around subclassing no?

**Comment by FedeClaudi** [comment]
that's correct. As per above, it's the only solution I've found to avoid having to define a bunch of classes..

**Comment by vigji** [comment]
Sorry, was typing at the same time :) 
But also, what do you need here that is BrainRender specific that would not actually be useful to have in `brainatlas_api`? All the get_colors_from_coordinates, get_hemisphere_from_point, etc would be good to have there - if not implemented already

**Comment by vigji** [comment]
I see your problem on avoiding defining one class per each BGAtlas, that's why I am thinking about it - the most straightforward way would be to just work with the brainatlas class, once it has feature parity

**Comment by FedeClaudi** [comment]
Yep, most functions below this line have or should be moved to brainatlas api:
https://github.com/BrancoLab/BrainRender/blob/99e986239a291c9dfd64da766485f7870c398dad/brainrender/atlases/brainglobe.py#L159


The only think I really need is [`get_brain_regions`](https://github.com/BrancoLab/BrainRender/blob/99e986239a291c9dfd64da766485f7870c398dad/brainrender/atlases/brainglobe.py#L41) which is specific to brainrender... 

And a few methods from the [base atlas](https://github.com/BrancoLab/BrainRender/blob/99e986239a/brainrender/atlases/base.py) like those to get planes etc. 
They return vedo actors, so not sure if it makes sense to have them in the api..

**Comment by vigji** [comment]
I think that methods for getting planes would be good to have in bgatlas, but just to grab numpy arrays of images - true that vedo actors should not be handled there.

Probably the best way would be to have a function like create_bg_atlas() that takes as an input a brainatlas_api atlas name, and then generate dynamically a child from BrainGlobeAtlasBase and the appropriate BrainGlobe parent!

The syntax should be something like `NewChile = type("Atlas", (BGAtlas, BrainGlobeAtlasBase), {})`

**Comment by FedeClaudi** [comment]
I think I tried something like that but with no success... will give it another shot..

**Comment by vigji** [comment]
I can try a PR tomorrow if you want!

**Comment by FedeClaudi** [comment]
sure!

**Comment by FedeClaudi** [comment]
Hey I've refactored the `atlases` module in brainrender.

Now there's only one [atlas class](https://github.com/BrancoLab/BrainRender/blob/75c1320253f21043bcd9fd914aa59df00fddc09f/brainrender/atlases/atlas.py#L9) which brings together all of brainrender and bg_atlaspi functionality. 

Hopefully this is a bit more elegant...

**Comment by vigji** [comment]
It is!
If you can excuse a little unrequested comment though, I believe it is not very kosher to have a parent inherited for which the init call is optional (`ABA`), and it does produce some funny behavior (eg, atlases will always be instances of ABA even if __init__ is not called). Not sure what's the cleanest workaround though.

**Comment by FedeClaudi** [comment]
yeah I know, it's still not very clean... I could rename `initi` in `ABA` to something else, but it wouldn't change much...

**Comment by vigji** [comment]
What about keeping 2 separate classes with the second one being a child of Atlas and ABA, and if you like default this second one in your scene? That might overall being the cleanest way, and more opened in the future to other classes with special add-ons

**Comment by FedeClaudi** [comment]
that sounds good. I think I will leave it as it for now though. Tt will probably need some fixes again once we finalise the release of brainglobe api anyway, so I might change it then.
