### ISSUE TITLE
BUG: new kim atlas not rendering in jupyter

### ISSUE THREAD

**Issue by opavon** [BrancoLab/BrainRender#86]
I'm using the brainglobeintegration branch on a laptop with Windows 10 with:
`brainrender               0.4.0.1`
`vedo                         2020.3.3`
`vtk                            8.1.2`
`vtkplotter                 2020.3.1`

Trying to render a scene with a couple of brain regions works as expected from a script (.py) but it fails to render anything when running from a jupyter notebook (.ipynb). When in the jupyter notebook, no error is thrown, it just prints the following without opening the window with the rendering: 
> Setting window size to 'auto' as whole screen is not available in jupyter
> The scene is ready to render in your jupyter notebook

Code:
`import brainrender`
`from brainrender.scene import Scene`
`from brainrender.colors import makePalette, get_random_colors`
`from vtkplotter import embedWindow`
`embedWindow(False)  # Disables scene embedding in jupyter notebooks`
`scene = Scene(display_inset = False, title = None, camera = "sagittal", atlas = 'kim_unified_50um_v0.1')`
`scene.add_brain_regions(['DLPAG', 'DMPAG', 'LPAG', 'VLPAG'], colors = get_random_colors(4), use_original_color = False)`
`scene.render(interactive = True, video = False, camera = "sagittal", zoom = 1)`

**Comment by marcomusy** [comment]
first off I would try
`pip uninstall vtkplotter`
and
`from vedo import embedWindow`

**Comment by opavon** [comment]
Cool! Just changing `from vtkplotter import embedWindow` to `from vedo import embedWindow` solved it. Thanks!

**Comment by FedeClaudi** [comment]
Nice, thanks @marcomusy  :)

**Comment by marcomusy** [comment]
de nada :)
