### ISSUE TITLE
brainglobeintegration branch - define colors used in "color_by_metadata" and "colors"

### ISSUE THREAD

**Issue by opavon** [BrancoLab/BrainRender#88]
Would it be possible to manually set the colors when using `color_by_metadata` in `scene.add_cells`  and `colors` in `scene.add_brain_regions`, so you can give it a list of 'x' number of colors and assign it to each of the metadata values? 

Something similar to the `mouselight.py` examples where `color_by_metadata = dict(metadata_value_1="blackboard", metadata_value_2="olivedrab", metadata_value_3="lightgreen")` or `colors = dict(MOs="blackboard", DRN="olivedrab", IC="lightgreen", LP="red"), use_original_color = False)`.

Thanks!

**Comment by FedeClaudi** [comment]
Done!

If you update from the branch, you will find that when using the `color_by_metadata` option, if you also pass a dictionary to `color` this dictionary will be used to map metadata values to colors. 
Obviously you need to make sure that your dictionary has an entry for each value that the metadata column you've specified takes in your dataset. 

Let me know if you have any problem with it :)

**Comment by opavon** [comment]
Awesome! I just gave it a try and `scene.add_cells(coords, color_by_metadata = "metadata_field", color = dict(metadata_value1 = "red", metadata_value2 = "blue")` works perfectly. Thanks!
