### ISSUE TITLE
density estimation from cloud of labeled cells

### ISSUE THREAD

**Issue by tbslv** [BrancoLab/BrainRender#89]
Ciao Federico, 

I was wondering if you've considered to integrate a function that does a 3D density estimation of labeled cells.

something very similar to this thread (https://stackoverflow.com/questions/25286811/how-to-plot-a-3d-density-map-in-python-with-matplotlib , ANSWER 1).

I have seen that vktplotter has a pointdensity function (https://vtkplotter.embl.es/_modules/vtkplotter/analysis.html )that would do the job. The problem I see here is that the function takes a mesh object as input and in order to create a mesh from a pointcloud the data needs to be 'noise-free' i.e. follow a clear surface/shape. 

All the best

**Comment by marcomusy** [comment]
Note that you can plug in this in `vedo` and it will work:
```python
import numpy as np
from scipy import stats
import multiprocessing
from vedo import Volume

n, mu, sigma = 5000, 0, 0.1
N = 30j
x = np.random.normal(mu, sigma, n)
y = np.random.normal(mu, sigma, n) + x
z = np.random.normal(mu, sigma, n)

xyz = np.vstack([x,y,z])
kde = stats.gaussian_kde(xyz)

# Evaluate kde on a grid
xmin, ymin, zmin = x.min(), y.min(), z.min()
xmax, ymax, zmax = x.max(), y.max(), z.max()
xi, yi, zi = np.mgrid[xmin:xmax:N, ymin:ymax:N, zmin:zmax:N]

# Multiprocessing
def calc_kde(data): return kde(data.T)
coords = np.vstack([item.ravel() for item in [xi, yi, zi]])
cores = multiprocessing.cpu_count()
pool = multiprocessing.Pool(processes=cores)
results = pool.map(calc_kde, np.array_split(coords.T, 2))
density = np.concatenate(results).reshape(xi.shape)
density = np.transpose(density, axes=[2,1,0])

vol = Volume(density, mode=1).color('jet')
vol.addScalarBar3D()
vol.show(axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/85541285-284fa500-b618-11ea-9494-ea8779b7aa1a.png)

> The problem I see here is that the function takes a mesh object as input and in order to create a mesh from a pointcloud the data needs to be 'noise-free' i.e. follow a clear surface/shape.

Not necessarily. This actually works faster and you don't need to transform the output volume:
```python
import numpy as np
from vedo import Volume, pointDensity, Points

n, mu, sigma = 5000, 0, 0.1
x = np.random.normal(mu, sigma, n) +10
y = np.random.normal(mu, sigma, n) + x
z = np.random.normal(mu, sigma, n)

vol = pointDensity(Points([x,y,z]))
vol.mode(1).color('jet').addScalarBar3D()
vol.show(axes=1)
```

**Comment by tbslv** [comment]
amazing!

thank you so much!

**Comment by FedeClaudi** [comment]
Hey, 
Thanks for opening up an issue on this.

>  that does a 3D density estimation of labeled cells

In general the answer for this kind of features will be no. That's because I'd like to keep the scope of brainrender limited to visualisation, including as little data processing/analysis as necessary. This is to keep the package lightweight and easy to maintain.  More specifically, you can generally check [neuro](https://github.com/SainsburyWellcomeCentre/neuro) for this kind of things or open an issue there if you can't find what you're looking for, @adamltyson  is great at these things. 


@marcomusy  I had missed `pointDensity`, that's awesome! Thanks for posting that here. 
@tbslv  you can integrate Marco's answer in brainrender by adding `vol` to your scenes with `scene.add_vtkactor(vol)` [note that this method will be renamed to `add_vedoactor` in future releases.]

**Comment by marcomusy** [comment]
> note that this method will be renamed to `add_vedoactor` in future releases.

why not calling it simply `scene.add()`, then inside add you might use `isinstance()` to dispatch the passed object to the right target,
..just an idea :) maybe you already have reasons not to do it..

**Comment by FedeClaudi** [comment]
I hadn't thought about it before.. 

The problem is that there's a ton of methods that add stuff to scenes and generally this is done not by passing object to the methods. Rather functions like `add_brain_regions` download, load and render data based on what the student requested. 
So I wouldn't want to have all these methods fall under a single `add` method. 

I might rename `add_vedoactor` to just `add` for brevity and perhaps have `add_from_file` fall under its scope.

**Comment by tbslv** [comment]
hey fede it's me again. 

I'm not able to change the color or opacity of the rendered volume. Here is the code snippet:

vol = pointDensity(Points(.x,y,z]))

scene = Scene()
scene.add_vtkactor(vol.c('r'))
scene.render()

Is it actually possible to do that?

**Comment by FedeClaudi** [comment]
That would work if `vol` was a `Mesh` object from `vedo`.
Instead `pointDensity` reuturns a [`Volume`](https://github.com/marcomusy/vedo/blob/b652bb773bde2ede5bb7dde8a38761fd4ff2dd8a/vedo/volume.py) object, which behaves a bit different. 
@marcomusy  might correct me if I'm wrong, but I don't think that `vol.c('r')` would work to change the color of the volume. 

I don't know if there's a way to pass colors/colormaps to `pointDensitiy`?

**Comment by marcomusy** [comment]
> Is it actually possible to do that?

As Federico says `pointDensity` outputs a Volume, so you change the coloring by setting a colormap like in the example above
`vol.color('jet')` (any matplotlib cmap name will work)
or by manually setting a set of colors (evenly spaced) along the scalar range:
`vol.color(['red', 'blue', 'pink'])`
Setting:
`vol.color('red')` also works but i guess the outcome will look pretty boring :)

Same syntax applies to transparency;
`vol.alpha([0,0,0.1,0.9])` 
will make invisible low values of the scalar and very opaque high values.

**Comment by tbslv** [comment]
I have tried it that way in the beginning. That doesn't work either.

**Comment by tbslv** [comment]
![Capture](https://user-images.githubusercontent.com/30258060/85737345-98852600-b6ff-11ea-8967-1fb84f2def79.PNG)

**Comment by tbslv** [comment]
SORRY, it works now. An update was the trick. thanks a lot for your help! 
best

**Comment by marcomusy** [comment]
nice, you may wish to try 
`vol.mode(1).jittering(True).c('Paired_r')`
to get some interesting coloring scheme:
![image](https://user-images.githubusercontent.com/32848391/85742261-61b10f00-b703-11ea-89c5-56d3aabfe785.png)

**Comment by FedeClaudi** [comment]
Hi all, the density mode from vedo is not fully integrated in brainrender: https://github.com/brainglobe/brainrender/blob/ad524f9e10898492ff8aeb1f31c69bf43b4f6d3c/brainrender/actors/points.py#L102

See this example to learn how to use it:
 https://github.com/brainglobe/brainrender/blob/master/examples/volumetric_data.py
