### ISSUE TITLE
Rendering style

### ISSUE THREAD

**Issue by jt522** [BrancoLab/BrainRender#90]
Hello,

The rendering styles are different before the update (2~3 month ago?) and the current version.
After the update, the brain looks more flat.
Is there any settings that I can render the brain in the previous style?
The first image is from the current version
the second is from previous version

Thanks!

![current](https://user-images.githubusercontent.com/13648214/87504064-c0e3ae80-c633-11ea-9205-0311cf3830f0.png)
<img width="1680" alt="previous" src="https://user-images.githubusercontent.com/13648214/87504093-d0fb8e00-c633-11ea-830a-2ed2783c3ba7.png">

**Comment by FedeClaudi** [comment]
Hi, 

Sorry just to check, which version of brainrender are you currently using?
And what code did you use for this plot?

The way to change the looks is to use
```
import brainrender
brainrender.SHADER_STYLE = "XXX"
```

From the figure it looks like you have `cartoon` in the top figure  but the default should be `plastic`. 

Hope this helps, 
Federico

**Comment by jt522** [comment]
Hi Federico,

Thanks for your help!
I'm using version: 0.4.0.0

I changed the style to plastic but the rendered brain still looks like the top image I posted.

Here's my code. Could you take a look?


### We begin by adding the current path to sys.path to make sure that the imports work correctly
import sys
sys.path.append('../')
import os
import pandas as pd
import numpy as np

from vtkplotter import *

### Import variables
import brainrender
brainrender.SHADER_STYLE = 'plastic'
brainrender.ROOT_ALPHA = .1

### Import brainrender classes and useful functions
from brainrender.scene import Scene
from brainrender.Utils.data_io import listdir

scene = Scene()
actors = scene.add_brain_regions(['XII'], colors="ivory", alpha= 0.2, use_original_color=False)

scene.add_cells(file_names[1], color='DarkViolet', radius = 10, res = 15); # aqua forestgreen

vp = Plotter(axes=0)
vp.show(scene.get_actors())

Thanks!

**Comment by FedeClaudi** [comment]
Hi, 

Okay, that's curious. 

A thing to try to make sure everything is working correctly is set `brainrender.ROOT_ALPHA = 1`, if that doesn't change anything then there's something wrong. 
If that's the case, then you might want to replace:
```
vp = Plotter(axes=0)
vp.show(scene.get_actors())
```
with 
```
scene.render()
```


If changing `ROOT_ALPHA` is working, then you can play around with `SHADER_STYLE` values. The allowed values are:
```
[default,metallic,plastic,shiny,glossy,ambient,off]
```

`shiny` might be what you're looking for.

**Comment by jt522** [comment]
shiny, glossy, default give me the 3D-ish brain.
I changed multiple alpha, lighting parameters via "plotter" interactive window. 
But somehow the rendered brain always looks more gray compared to the brain I previously plotted.
Do you think where I can change?

![K3D-1594822920207](https://user-images.githubusercontent.com/13648214/87558941-ac310600-c687-11ea-81bf-37a7049bc30f.png)

**Comment by FedeClaudi** [comment]
sorry I'm not sure I understand, are those parameters changing the way the render looks, or are they not changing anything?

If it's the color that you want to change, you can try playing around with `brainrender.ROOT_COLOR` and increase it to something like `[.8, .8, .8]` for instance. It's `[.4, .4, .4]` by default.

**Comment by jt522** [comment]
Sorry. I didn't explain well. Those parameters do change the way the render looks. The root alpha/opacity around 0.2 ~ 0.3 with 'plastic' gives me good 3D effect/shading I want. But with this setting, inside the brain is dark gray even if I use brighter brainrender.ROOT_COLOR. I would like to get the look similar to the image in my first comment or your examples like this. In those rendered brains, the color inside the brain is light gray, and the surface still maintains the shading. 

<img width="262" alt="image" src="https://user-images.githubusercontent.com/13648214/87567098-de476580-c691-11ea-80d5-25abc21f4bb6.png">

**Comment by FedeClaudi** [comment]
mmm, I see. I think you can then leave `SHADER_STYLE` to its default value and just play around with `ROOT_ALPHA` and `ROOT_COLOR`. That's the only two parameters that affect that. 

I don't remember exactly what values I've used to generate that image, but these seem to get results similar to it:
```
brainrender.ROOT_COLOR = [.8, .8, .8]
brainrender.ROOT_ALPHA = .2
```


<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/87570948-41042580-c6c1-11ea-8b0c-fcd74eb0b261.png">

**Comment by jt522** [comment]
I still don't get the same look.
After I run these lines, 

vp = Plotter(axes=0)
vp.show(scene.get_actors())

I get a black background window and I get a white background image after "screenshot".
Do you think that's the reason?

<img width="986" alt="image" src="https://user-images.githubusercontent.com/13648214/87579630-36876300-c6a4-11ea-8ec1-4d9b17a37e0f.png">

**Comment by FedeClaudi** [comment]
But I don't understand why you're using 
```
vp = Plotter(axes=0)
vp.show(scene.get_actors())
```

instead of
```
scene.render()
```
?

Are you using a jupyter notebook?
If so, I'd suggest **not** doing that, it does make things a bit more difficult with brainrender at this stage unfortunately. 

The black background might be due to `brainrender.SCREENSHOT_TRANSPARENT_BACKGROUND`, you could try setting it to `False`, by default it's `True` but that might not work well with the backend used in the notebooks.

**Comment by jt522** [comment]
Yes, I'm using jupyter. I will try spyder.

When I use "scene.render()"
I get this error. Could you tell me how to avoid this?

Thanks!
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-123657683ae1> in <module>
----> 1 scene.render()

/opt/anaconda3/lib/python3.7/site-packages/brainrender/scene.py in render(self, interactive, video, camera, zoom, **kwargs)
   1095                                         camera = check_camera_param(camera)
   1096 
-> 1097                                 set_camera(self, camera)
   1098 
   1099                         if interactive:

/opt/anaconda3/lib/python3.7/site-packages/brainrender/Utils/camera.py in set_camera(scene, camera)
    114 
    115         # set params
--> 116         set_camera_params(scene.plotter.camera, camera)
    117     else:
    118         scene.plotter.camera = camera

/opt/anaconda3/lib/python3.7/site-packages/brainrender/Utils/camera.py in set_camera_params(camera, params)
     91 def set_camera_params(camera, params):
     92     # Apply camera parameters
---> 93     camera.SetPosition(params['position'])
     94     camera.SetFocalPoint(params['focal'])
     95     camera.SetViewUp(params['viewup'])

AttributeError: 'NoneType' object has no attribute 'SetPosition'

**Comment by FedeClaudi** [comment]
Hi, 

No sorry with the version of brainrender you're using `scene.render()` won't work in a notebook, it will be fixed in a future release. 

I would suggest trying to not use notebooks if you can, but if you really want to then it might be a better idea to use another backend. 

You can try adding these two lines before the scene creation:
```
from vedo import embedWindow
embedWindow(False) 
```

see [here](https://github.com/marcomusy/vedo/blob/master/notebooks/tutorial.ipynb) for more details.

**Comment by FedeClaudi** [comment]
I will close for now, but let me know if there's something you're not happy with.

**Comment by jt522** [comment]
Hi Federico,
Sorry to get back to you late.
Now I get the good rendering in Jupyter with 

from vedo import embedWindow
embedWindow(False) 

Thanks for your help as always!

**Comment by FedeClaudi** [comment]
excellent! thanks, and enjoy!
