### ISSUE TITLE
[BUG] KeyError: 'No object named hdf in the file'

### ISSUE THREAD

**Issue by rdbcasillas** [BrancoLab/BrainRender#97]
**Describe the bug**
When I try to add cells:

```
scene.add_cells_from_file("C:\\Users\\Administrator\\Documents\\164-brainrender-test\\standard_space\\exported_cells_yxz.h5")
```

I get the following error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-5-6a3cfd07e8ae> in <module>
----> 1 scene.add_cells_from_file("C:\\exported_cells.h5")

c:\users\administrator\miniconda3\envs\brainrender\lib\site-packages\brainrender\scene.py in add_cells_from_file(self, filepath, hdf_key, color, radius, res, alpha)
    608                                         hdf_key = brainrender.DEFAULT_HDF_KEY
    609                                 try:
--> 610                                         cells = pd.read_hdf(filepath, key=hdf_key)
    611                                 except TypeError:
    612                                         if hdf_key == brainrender.DEFAULT_HDF_KEY:

c:\users\administrator\miniconda3\envs\brainrender\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    405                     )
    406             key = candidate_only_group._v_pathname
--> 407         return store.select(key, auto_close=auto_close, **kwargs)
    408     except (ValueError, TypeError, KeyError):
    409         # if there is an error, close the store

c:\users\administrator\miniconda3\envs\brainrender\lib\site-packages\pandas\io\pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
    755         group = self.get_node(key)
    756         if group is None:
--> 757             raise KeyError("No object named {key} in the file".format(key=key))
    758 
    759         # create the storer and axes

KeyError: 'No object named hdf in the file'

```

**To Reproduce**
Name: brainrender
Version: 0.4.0.0

Converted cellfinder's output xml file into _**.h5**_ file using ```points_to_brainrender``` functionality. 

```
import brainrender
brainrender.SHADER_STYLE = 'cartoon'
from brainrender.scene import Scene
import pandas as pd
scene = Scene(camera='top', jupyter='True')
scene.add_cells_from_file("C:\\Users\\Administrator\\Documents\\164-brainrender-test\\standard_space\\exported_cells_yxz.h5")
```

**Expected behavior**
Cells get added to the scene

**Comment by FedeClaudi** [comment]
Hi,

Thanks for the detailed report.
could you try upgrading to brainrender 1.0.0 please?

```
pip install brainrender-U
```

**Comment by rdbcasillas** [comment]
Hi @FedeClaudi ,

Upgrading took care of that error.  But now an old command is not working: 

```
vp.show(scene.get_actors())

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-008c24db9e21> in <module>
----> 1 vp.show(scene.get_actors())

AttributeError: 'Scene' object has no attribute 'get_actors'

```

Another error that may cause problems with Jupyter is that I can no longer use : 

```scene = Scene(camera='top', jupyter='True')``` 


The reason I downgraded was because I got an error with **cellfinder_view** which is dependent on brainrender. Also, I happen to have an old installation of same version of brainrender on separate conda environment (on separate computer) which surprisingly seems to be working fine.

**Comment by FedeClaudi** [comment]
Hi,

I see, for the first problem this might help https://docs.brainrender.info/usage/using-notebooks

For cell finder, I don't know if @adamltyson is planning to update the dependency any time soon, but meanwhile you can have the older brainrender in the environment you use for cell finder and the never one in a separate environment.

Alternatively, with brainrender 0.4.0 you can load the cells in python (eg `pandas.read_hdf` and then use `scene.add_cells` to get around the initial error you've reported.

**Comment by rdbcasillas** [comment]
>I see, for the first problem this might help https://docs.brainrender.info/usage/using-notebooks

This did not resolve the error I got after using ```vp.show(scene.get_actors())``` 

Were you referring to following section in the documentation? 

![image](https://user-images.githubusercontent.com/9725334/89435364-646f3d00-d762-11ea-9e3d-c10fad5be275.png)

**Comment by FedeClaudi** [comment]
Sorry it looks like the docs are a bit out dated as well... Instead of `scene.get_actors()` you can use `scene.actors` (without the parenthesis).

Hope this helps!

**Comment by rdbcasillas** [comment]
Thanks! Removing parenthesis worked. The documentation should say ```vp.show(scene.actors)```
