### ISSUE TITLE
[BUG] Cell coordinates produced by cellfinder don't align when mapped onto brainrender's default brain. 

### ISSUE THREAD

**Issue by rdbcasillas** [BrancoLab/BrainRender#98]
**Describe the bug**
I am not sure if I should ask this here or at cellfinder's github repo maintained by @adamltyson . But I have been trying to map cellfinder's output cell locations onto brainrender's root brain. For this, I followed the steps [here](https://docs.cellfinder.info/neuro/standalone-tools/exporting-detected-cell-positions-to-brainrender#to-visualise-this-file-in-brainrender) and imported the .h5 file into brainrender. I noticed that after rendering the cells, they are misaligning. X,Y,Z coordinates of cell locations (within xml file generated by cellfinder in **standard_space** folder) aren't mapping correctly onto the brainrender's root brain image. 

I tried swapping the coordinates (convert X to Z, X to Y, Y to Z etc.)  but that is not really helping. Following is an image that highlights what I mean when I say misaligning of cells onto brainrender's default root brain image: 

![image](https://user-images.githubusercontent.com/9725334/89455387-e15cdf80-d77f-11ea-8308-63e2a9f6fc6a.png)

The X,Y,Z coordinates are off and don't align properly to the root brain image. I am wondering if there are any parameters within brainrender that I can modulate to better fit the cellfinder's **points_to_brainrender** output. 

Thanks @FedeClaudi for your work on this and active response to issues.

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for getting in touch. Is this with brainrender 1.0? If so that might be a hint to what went wrong, though ultimately only @adamltyson will know the whats causing this.

Just to be clear,in which way are they not aligned? It looks like the Y axis might be inverted?

**Comment by rdbcasillas** [comment]
This happens with both 0.4 and 1.0. 

>Just to be clear,in which way are they not aligned? It looks like the Y axis might be inverted?

That's the concern, it is hard to know what exactly is inverted or flipped. We have only tried swapping dimensions like **MarkerX** with **MarkerY**  or **MarkerZ** with **MarkerX**  (within cellfinder's xml file).  [Here's](https://gist.github.com/rdbcasillas/ac6c1c7922528025e6982d707d65d21e) one of the xml files we are trying to load onto brainrender at the moment. 

If @adamltyson wants me to open this as an issue at cellfinder and provide him with full cellfinder output, I am happy to do that.

**Comment by adamltyson** [comment]
Hi @rdbcasillas, sorry about this, it might be a cellfinder issue.

What orientation is your data in (coronal, saggital, horizontal), and which is the first plane in your stack (posterior, superior, left etc.)? 

The cells -> brainrender functionality isn't very robust at the moment, but I'm aiming to fix this when [brainreg](https://github.com/brainglobe/brainreg) replaces amap in cellfinder.

**Comment by rdbcasillas** [comment]
>What orientation is your data in (coronal, saggital, horizontal), and which is the first plane in your stack (posterior, superior, left etc.)?

Horizontal orientation.  First plane is posterior (ventral). Let me know if you need more info. 

>The cells -> brainrender functionality isn't very robust at the moment, but I'm aiming to fix this when brainreg replaces amap in cellfinder.

Thank you! Do you have an approximate timeline for this?

**Comment by adamltyson** [comment]
> Horizontal orientation. First plane is ventral. Let me know if you need more info.

I think this is likely the issue, I released the `points_to_brainrender` functionality public very hastily, and I think it only works properly for coronal data. 

> Thank you! Do you have an approximate timeline for this?

Hopefully soon, it's very overdue, but I've got a lot on at the minute. 

If you wanted to take a look at it, I think you should be able to just swap the x/y/z around in the conversion script [here](https://github.com/SainsburyWellcomeCentre/neuro/blob/bbe7865ef8d3191b256f3453c061e56f8af01a86/neuro/points/points_to_brainrender.py#L35). The script is pretty simple, so I hope it makes sense.

**Comment by rdbcasillas** [comment]
Thank you @adamltyson for pointing me to the script! Seems understandable so I will play with it.
